### ISSUE TITLE
An exception I got related to dcd.

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#194]
```
The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 8,4,main]
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 8,4,main]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2086)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1245)
	at com.intellij.openapi.ui.Messages$MessageDialog._init(Messages.java:1388)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1313)
	at com.intellij.openapi.ui.Messages.showIdeaMessageDialog(Messages.java:187)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:174)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:143)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:691)
	at net.masterthought.dlanguage.project.DubConfigurationParser.parseDubConfiguration(DubConfigurationParser.java:154)
	at net.masterthought.dlanguage.project.DubConfigurationParser.<init>(DubConfigurationParser.java:35)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.spawnProcess(DCDCompletionServer.java:127)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.exec(DCDCompletionServer.java:87)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:48)
	at net.masterthought.dlanguage.codeinsight.DCompletionContributor$2.addCompletions(DCompletionContributor.java:45)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:803)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:785)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 8,4,main]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2086)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1245)
	at com.intellij.openapi.ui.Messages$MessageDialog._init(Messages.java:1388)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1313)
	at com.intellij.openapi.ui.Messages.showIdeaMessageDialog(Messages.java:187)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:174)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:143)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:691)
	at net.masterthought.dlanguage.project.DubConfigurationParser.parseDubConfiguration(DubConfigurationParser.java:154)
	at net.masterthought.dlanguage.project.DubConfigurationParser.<init>(DubConfigurationParser.java:35)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.spawnProcess(DCDCompletionServer.java:127)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.exec(DCDCompletionServer.java:87)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:48)
	at net.masterthought.dlanguage.codeinsight.DCompletionContributor$2.addCompletions(DCompletionContributor.java:45)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:803)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:785)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 5,4,main]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2086)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1245)
	at com.intellij.openapi.ui.Messages$MessageDialog._init(Messages.java:1388)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1313)
	at com.intellij.openapi.ui.Messages.showIdeaMessageDialog(Messages.java:187)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:174)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:143)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:691)
	at net.masterthought.dlanguage.project.DubConfigurationParser.parseDubConfiguration(DubConfigurationParser.java:154)
	at net.masterthought.dlanguage.project.DubConfigurationParser.<init>(DubConfigurationParser.java:35)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.spawnProcess(DCDCompletionServer.java:127)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.exec(DCDCompletionServer.java:87)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:48)
	at net.masterthought.dlanguage.codeinsight.DCompletionContributor$2.addCompletions(DCompletionContributor.java:45)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:803)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:785)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 5,4,main]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2086)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1245)
	at com.intellij.openapi.ui.Messages$MessageDialog._init(Messages.java:1388)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1313)
	at com.intellij.openapi.ui.Messages.showIdeaMessageDialog(Messages.java:187)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:174)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:143)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:691)
	at net.masterthought.dlanguage.project.DubConfigurationParser.parseDubConfiguration(DubConfigurationParser.java:154)
	at net.masterthought.dlanguage.project.DubConfigurationParser.<init>(DubConfigurationParser.java:35)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.spawnProcess(DCDCompletionServer.java:127)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.exec(DCDCompletionServer.java:87)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:48)
	at net.masterthought.dlanguage.codeinsight.DCompletionContributor$2.addCompletions(DCompletionContributor.java:45)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:803)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:785)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 6,4,main]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2086)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1245)
	at com.intellij.openapi.ui.Messages$MessageDialog._init(Messages.java:1388)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1313)
	at com.intellij.openapi.ui.Messages.showIdeaMessageDialog(Messages.java:187)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:174)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:143)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:691)
	at net.masterthought.dlanguage.project.DubConfigurationParser.parseDubConfiguration(DubConfigurationParser.java:154)
	at net.masterthought.dlanguage.project.DubConfigurationParser.<init>(DubConfigurationParser.java:35)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.spawnProcess(DCDCompletionServer.java:127)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionServer.exec(DCDCompletionServer.java:87)
	at net.masterthought.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:48)
	at net.masterthought.dlanguage.codeinsight.DCompletionContributor$2.addCompletions(DCompletionContributor.java:45)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:803)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:785)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


```

Anybody know what caused this?

**Comment by pirocks** [comment]
This can be fixed by changing DubConfigurationParser.java:156 to:
```
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        Messages.showErrorDialog(project, String.format("%s exited with %s", dubCommand, exitCode), "Dub Import");
                    }
                });
```

There are likely other places where this needs to be done throughout.

**Comment by pirocks** [comment]
Another issue this exception raises is that `dub describe` was being run on a non-dub project.

**Comment by SingingBush** [comment]
I pushed the change you've suggested. It seems that your branch is missing changes though as that line was actually 200 not 156. I should get time to take a look this week

**Comment by pirocks** [comment]
Okay. I'll make sure to pull changes
