### ISSUE TITLE
Exception when DScanner path defined

### ISSUE THREAD

**Issue by dmi7ry** [intellij-dlanguage/intellij-dlanguage#222]
First start of the project (Start IDE, load project, Shift+F10) always shows error (exception in plugin D Language):

    2017-08-06T15:41:10.063:dsymbol\src\dsymbol\conversion\first.d:visit:307 Could not locate object.d or object.di

    java.lang.Throwable
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
        at net.masterthought.dlanguage.highlighting.annotation.external.DScanner$1.onTextAvailable(DScanner.java:66)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
        at com.sun.proxy.$Proxy15.onTextAvailable(Unknown Source)
        at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:201)
        at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:295)
        at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
        at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
        at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
        at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
        at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
        at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:194)
        at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

P.S. Some info:
Windows 7 x64

IntelliJ IDEA 2017.2.1
Build #IC-172.3544.35, built on July 31, 2017
JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

D Language 1.13

**Comment by dmi7ry** [comment]
**Upd**: Oh, it happens even when I just write a code

**Comment by dmi7ry** [comment]
Looks like the problem gone after I rebuilt dscanner (even version is same). I'll test it more.
