### ISSUE TITLE
Unclosed token strings can cause NPE in DLangParser.advance

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#247]
StackTrace:

```
null
java.lang.NullPointerException
	at net.masterthought.dlanguage.parser.DLangParser.advance(DLangParser.java:8524)
	at net.masterthought.dlanguage.parser.DLangParser.parsePrimaryExpression(DLangParser.java:5781)
	at net.masterthought.dlanguage.parser.DLangParser.unaryExpressionSwitchDefault(DLangParser.java:7575)
	at net.masterthought.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.java:7700)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:9079)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parsePowExpression(DLangParser.java:5577)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:9057)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parseMulExpression(DLangParser.java:5132)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:9047)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parseAddExpression(DLangParser.java:457)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:8991)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parseShiftExpression(DLangParser.java:6005)
	at net.masterthought.dlanguage.parser.DLangParser.parseCmpExpression(DLangParser.java:2210)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:9027)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parseAndExpression(DLangParser.java:710)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:8995)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parseXorExpression(DLangParser.java:8014)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:9081)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parseOrExpression(DLangParser.java:5326)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:9053)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parseAndAndExpression(DLangParser.java:688)
	at net.masterthought.dlanguage.parser.DLangParser.parseName(DLangParser.java:8993)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8284)
	at net.masterthought.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8276)
	at net.masterthought.dlanguage.parser.DLangParser.parseOrOrExpression(DLangParser.java:5354)
	at net.masterthought.dlanguage.parser.DLangParser.parseTernaryExpression(DLangParser.java:7123)
	at net.masterthought.dlanguage.parser.DLangParser.parseAssignExpression(DLangParser.java:1533)
	at net.masterthought.dlanguage.parser.DLangParser.parseNonVoidInitializer(DLangParser.java:5276)
	at net.masterthought.dlanguage.parser.DLangParser.parseInitializer(DLangParser.java:4681)
	at net.masterthought.dlanguage.parser.DLangParser.parseAutoDeclarationPart(DLangParser.java:1829)
	at net.masterthought.dlanguage.parser.DLangParser.parseAutoDeclaration(DLangParser.java:1786)
	at net.masterthought.dlanguage.parser.DLangParser.parseVariableDeclaration(DLangParser.java:7841)
	at net.masterthought.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:2676)
	at net.masterthought.dlanguage.parser.DLangParser.parseModule(DLangParser.java:5086)
	at net.masterthought.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:413)
	at net.masterthought.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:422)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:246)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.a(DefaultStubBuilder.java:123)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:93)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:83)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:58)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.a(StubUpdatingIndex.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:211)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:194)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1615)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1551)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1510)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1477)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1633)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1630)
	at com.intellij.util.indexing.UpdateTask.a(UpdateTask.java:80)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:47)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1652)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:696)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:662)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:346)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:96)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:131)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:131)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:108)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createTypeByFQClassName(PsiElementFactoryImpl.java:421)
	at com.intellij.psi.PsiType.getTypeByName(PsiType.java:168)
	at com.intellij.psi.PsiType.getJavaLangObject(PsiType.java:180)
	at com.intellij.psi.impl.PsiClassImplUtil.getSuperTypes(PsiClassImplUtil.java:864)
	at com.intellij.psi.impl.compiled.ClsClassImpl.getSuperTypes(ClsClassImpl.java:150)
	at com.intellij.psi.impl.ScopedClassHierarchy.calcImmediateSupersWithCapturing(ScopedClassHierarchy.java:166)
	at com.intellij.psi.impl.ScopedClassHierarchy.lambda$getImmediateSupersWithCapturing$2(ScopedClassHierarchy.java:151)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.ScopedClassHierarchy.getImmediateSupersWithCapturing(ScopedClassHierarchy.java:151)
	at com.intellij.psi.impl.PsiClassImplUtil.getScopeCorrectedSuperTypes(PsiClassImplUtil.java:733)
	at com.intellij.psi.impl.PsiClassImplUtil.processSuperTypes(PsiClassImplUtil.java:743)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:718)
	at com.intellij.psi.impl.PsiClassImplUtil.access$200(PsiClassImplUtil.java:63)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:402)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:350)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:58)
	at com.intellij.psi.impl.PsiClassImplUtil.processCachedMembersByName(PsiClassImplUtil.java:518)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:478)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:455)
	at com.intellij.psi.impl.compiled.ClsClassImpl.processDeclarations(ClsClassImpl.java:459)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:238)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:227)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.multiResolve(PsiImportStaticReferenceElementImpl.java:223)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarationsNoGuess(PsiJavaFileBaseImpl.java:369)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:304)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:69)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:51)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:218)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:149)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToVariable(PsiReferenceExpressionImpl.java:341)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:252)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:56)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:192)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:181)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver$1.elementFinished(PsiReferenceExpressionImpl.java:230)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor$1.elementFinished(JavaRecursiveElementWalkingVisitor.java:35)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor$1.elementFinished(JavaRecursiveElementWalkingVisitor.java:32)
	at com.intellij.util.WalkingState.next(WalkingState.java:80)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:61)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
	at com.intellij.psi.JavaElementVisitor.visitExpression(JavaElementVisitor.java:102)
	at com.intellij.psi.JavaElementVisitor.visitCallExpression(JavaElementVisitor.java:186)
	at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:182)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:141)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolveAllQualifiers(PsiReferenceExpressionImpl.java:213)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:191)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:181)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:187)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:724)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:715)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:348)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.advancedResolve(PsiReferenceExpressionBase.java:86)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.resolve(PsiReferenceExpressionBase.java:48)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.resolveMethod(PsiMethodCallExpressionImpl.java:59)
	at com.intellij.psi.impl.source.resolve.graphInference.PsiPolyExpressionUtil.isPolyExpression(PsiPolyExpressionUtil.java:51)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:85)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getType(PsiMethodCallExpressionImpl.java:54)
	at org.jetbrains.uast.java.JavaAbstractUExpression.getExpressionType(JavaAbstractUElement.kt:53)
	at com.intellij.codeInsight.daemon.impl.IconLineMarkerProvider.getLineMarkerInfo(IconLineMarkerProvider.java:65)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:189)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


```

**Comment by pirocks** [comment]
This has been fixed.
