### ISSUE TITLE
Exception in getTreeBuilt(), reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#271]
Exception:
```
java.lang.Throwable: null
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
    at com.intellij.lang.impl.PsiBuilderImpl.a(PsiBuilderImpl.java:1079)
    at com.intellij.lang.impl.PsiBuilderImpl.a(PsiBuilderImpl.java:1071)
    at com.intellij.lang.impl.PsiBuilderImpl.h(PsiBuilderImpl.java:1092)
    at com.intellij.lang.impl.PsiBuilderImpl.g(PsiBuilderImpl.java:1013)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:917)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:912)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:424)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
    at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:851)
    at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:49)
    at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:31)
    at com.intellij.util.WalkingState.next(WalkingState.java:73)
    at com.intellij.util.WalkingState.walkChildren(WalkingState.java:61)
    at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
    at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
    at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
    at com.intellij.psi.util.PsiTreeUtil$3.visitElement(PsiTreeUtil.java:798)
    at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
    at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
    at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
    at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:793)
    at com.intellij.psi.util.PsiTreeUtil.findChildrenOfAnyType(PsiTreeUtil.java:299)
    at com.intellij.psi.util.PsiTreeUtil.findChildrenOfType(PsiTreeUtil.java:278)
    at io.github.intellij.dlanguage.features.DFoldingBuilder.buildFoldRegions(DFoldingBuilder.java:31)
    at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:241)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:227)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:216)
    at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:54)
    at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.a(AsyncEditorLoader.java:100)
    at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$2(PsiDocumentManagerBase.java:502)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
    at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:500)
    at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.a(AsyncEditorLoader.java:98)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
    at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.a(AsyncEditorLoader.java:98)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```
Additional Info provided by sentry:

Additional info: | "I invalided cache + restarted the IDE"
-- | --
App Build | "IU-172.4343.14"
App Full Name | "IntelliJ IDEA"
App Name | "IDEA"
App Version name | "IntelliJ IDEA"
App Version | "2017.2.5"
Is EAP | "false"
Java version | "1.8.0_152-release"
Java vm vendor | "JetBrains s.r.o"
Last Action | "EditorBackSpace"
OS Name | "Windows 10"

Sentry link: https://sentry.io/share/issue/f636cc9138bc4e91b5dc5fb7ae4b5554/

**Comment by pirocks** [comment]
This appears to be the same root cause as #248
