### ISSUE TITLE
NullPointerException in DFixAction reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#272]
Exception:
```
java.lang.NullPointerException: null
    at io.github.intellij.dlanguage.actions.DFixAction.update(DFixAction.java:40)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:132)
    at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:235)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:180)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:205)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:100)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:341)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:326)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:54)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:280)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
    at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
    at javax.swing.JMenu.setSelected(JMenu.java:305)
    at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1187)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:244)
    at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125)
    at javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:526)
    at java.awt.Component.processMouseEvent(Component.java:6550)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6306)
    at java.awt.Container.processEvent(Container.java:2237)
    at java.awt.Component.dispatchEventImpl(Component.java:4897)
    at java.awt.Container.dispatchEventImpl(Container.java:2295)
    at java.awt.Component.dispatchEvent(Component.java:4719)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
    at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4677)
    at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4655)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4506)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
    at java.awt.Container.dispatchEventImpl(Container.java:2281)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4719)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:737)
    at java.awt.EventQueue$4.run(EventQueue.java:735)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Sentry link:
https://sentry.io/share/issue/290589421cdf4428ad32ffc8451a2d8d/

Additional info:

Additional info: | None
-- | --
App Build | IC-172.4343.14
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version name | IntelliJ IDEA
App Version | 2017.2.5
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | WelcomeScreen.RemoveSelected
OS Name | Linux

**Comment by SingingBush** [comment]
the line that causes the problem is `e.getPresentation().setEnabled(DlangFile.class.isAssignableFrom(psiFile.getClass()));`
