### ISSUE TITLE
New logger error reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#273]
```java.lang.Throwable: null
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.getChildIndex(SharedPsiElementImplUtil.java:136)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.getPrevSibling(SharedPsiElementImplUtil.java:124)
    at com.intellij.psi.impl.PsiElementBase.getPrevSibling(PsiElementBase.java:62)
    at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.recurseUpImpl(DAttributesFinder.kt:91)
    at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.recurseUp(DAttributesFinder.kt:81)
    at io.github.intellij.dlanguage.features.DDocumentationProvider.generateDoc(DDocumentationProvider.java:50)
    at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:659)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:926)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:656)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
    at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
    at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
    at com.intellij.util.Alarm$Request.run(Alarm.java:395)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745
```

Additional info: | None
-- | --
App Build | IU-172.4343.14
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version name | IntelliJ IDEA
App Version | 2017.2.5
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | CommentByBlockComment
OS Name | Mac OS X

sentry link: https://sentry.io/share/issue/4a95f17dad8c4b1a99c31252d3a19234/

**Comment by pirocks** [comment]
This bug can no longer happen due to the refactoring of DAttributesFinder.
