### ISSUE TITLE
New error in dscanner reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#274]
```
java.lang.Throwable: null
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1063)
    at com.intellij.psi.impl.source.tree.CompositeElement.getTextLength(CompositeElement.java:514)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getTextLength(LazyParseableElement.java:117)
    at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:373)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.getOffsetEnd(DScanner.java:128)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.calculateTextRange(DScanner.java:145)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.parseProblem(DScanner.java:157)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.access$000(DScanner.java:29)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner$1.onTextAvailable(DScanner.java:87)
    at sun.reflect.GeneratedMethodAccessor45.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
    at com.sun.proxy.$Proxy17.onTextAvailable
    at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:201)
    at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:295)
    at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
    at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
    at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
    at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
    at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
    at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:194)
    at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Additional info: | I was just manually replacing spaces with tabs.
-- | --
App Build | IU-172.4343.14
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version name | IntelliJ IDEA
App Version | 2017.2.5
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | EditorLineEnd
OS Name | Windows 10

Sentry link: https://sentry.io/share/issue/8e521d4584634adf91e5e373b8713912/

**Comment by pirocks** [comment]
This has been reported a second time this time with the exception:
```
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:154)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1048)
    at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:258)
    at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:228)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getText(LazyParseableElement.java:97)
    at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:327)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.getOffsetStart(DScanner.java:57)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.calculateTextRange(DScanner.java:149)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.parseProblem(DScanner.java:162)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.access$000(DScanner.java:32)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner$1.onTextAvailable(DScanner.java:90)
    at sun.reflect.GeneratedMethodAccessor48.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:239)
    at com.sun.proxy.$Proxy16.onTextAvailable
    at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:213)
    at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:295)
    at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
    at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
    at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
    at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
    at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
    at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:194)
    at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
