### ISSUE TITLE
AssertionError in single import reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#275]
It seems this was from a previous plugin. I will still make sure that this is no longer an issue.

```
java.lang.AssertionError: null
    at io.github.intellij.dlanguage.psi.impl.named.DlangSingleImportImpl.getImportedModuleName(DlangSingleImportImpl.java:80)
    at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.getAllPubliclyImported(DImportIndex.kt:55)
    at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.recursivelyGetAllPublicImports(DImportIndex.kt:44)
    at io.github.intellij.dlanguage.resolve.processors.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:63)
    at io.github.intellij.dlanguage.resolve.processors.DNameScopeProcessor.execute(DNameScopeProcessor.kt:42)
    at io.github.intellij.dlanguage.resolve.ScopeProcessorImplUtil.processDeclaration(ScopeProcessorImplUtil.kt:77)
    at io.github.intellij.dlanguage.psi.DlangFile.processDeclarations(DlangFile.java:82)
    at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1103)
    at io.github.intellij.dlanguage.resolve.processors.basic.BasicResolve.findDefinitionNode(BasicResolve.kt:40)
    at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNodeImpl(DResolveUtil.kt:55)
    at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNode(DResolveUtil.kt:37)
    at io.github.intellij.dlanguage.inspections.PossiblyUndefinedSymbol$UndefinedSymbolVisitor.visitIdentifier(PossiblyUndefinedSymbol.kt:44)
    at io.github.intellij.dlanguage.psi.impl.named.DlangIdentifierImpl.accept(DlangIdentifierImpl.java:41)
    at io.github.intellij.dlanguage.psi.impl.named.DlangIdentifierImpl.accept(DlangIdentifierImpl.java:45)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:305)
    at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:133)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1142)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:237)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
    at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
    at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
    at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
    at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
    at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
    at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:63)
    at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:316)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:226)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:132)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:431)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:430)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:406)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:237)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Sentry link: https://sentry.io/share/issue/6161e77fd140419c97b374e2c295dcd2/

Additional info: | I was trying to type out this line: 	writeln( "Unknown index: " ~ pos ); Not sure exactly which character caused the problem, but as soon as this error message popped up, IDEA notified me of an update to this plugin.
-- | --
App Build | IU-172.4343.14
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version name | IntelliJ IDEA
App Version | 2017.2.5
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | EditorBackSpace
OS Name | Windows 10

**Comment by pirocks** [comment]
This seems to have been already fixed.
