### ISSUE TITLE
Kotlin null pointer exception reported by sentry 

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#277]
```
kotlin.KotlinNullPointerException: null at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.updateFromAttribute(DAttributesFinder.kt:193) at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.execute(DAttributesFinder.kt:134) at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.recurseUpImpl(DAttributesFinder.kt:88) at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.recurseUp(DAttributesFinder.kt:81) at io.github.intellij.dlanguage.psi.impl.named.DlangSingleImportImpl.isPublic(DlangSingleImportImpl.java:90) at io.github.intellij.dlanguage.stubs.types.SingleImportStubElementType.createStub(SingleImportStubElementType.java:37) at io.github.intellij.dlanguage.stubs.types.SingleImportStubElementType.createStub(SingleImportStubElementType.java:19) at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.createStub(DefaultStubBuilder.java:113) at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:88) at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:83) at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:58) at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39) at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86) at com.intellij.psi.stubs.StubUpdatingIndex$3.lambda$map$0(StubUpdatingIndex.java:212) at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:921) at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:211) at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:194) at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272) at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99) at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215) at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1615) at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$18(FileBasedIndexImpl.java:1551) at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518) at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1510) at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498) at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:105) at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:229) at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148) at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:246) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157) at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242) at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)
```

Sentry link:https://sentry.io/share/issue/9046d59a815a4abe90ac0dea54249bc5/

Additional info:NoneApp BuildIC-172.4343.14App Full NameIntelliJ IDEAApp NameIDEAApp Version nameIntelliJ IDEAApp Version2017.2.5Is EAPfalseJava version1.8.0_152-releaseJava vm vendorJetBrains s.r.oLast ActionOS NameLinux

**Comment by SingingBush** [comment]
@pirocks I started adding some tests for DAttributesFinder. Ideally all potential routes within _recurseUp()_ should have a test.
