### ISSUE TITLE
NPE in DFixAction reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#278]
```
java.lang.NullPointerException: null
    at io.github.intellij.dlanguage.actions.DFixAction.update(DFixAction.java:40)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:132)
    at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:235)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:180)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:205)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:100)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:341)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.b(ActionMenu.java:326)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:54)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:280)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1036)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1116)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:352)
    at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:234)
    at javax.swing.JMenu.setSelected(JMenu.java:291)
    at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1187)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:244)
    at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:127)
    at javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:579)
    at java.awt.Component.processMouseEvent(Component.java:6587)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3343)
    at java.awt.Component.processEvent(Component.java:6343)
    at java.awt.Container.processEvent(Container.java:2259)
    at java.awt.Component.dispatchEventImpl(Component.java:4961)
    at java.awt.Container.dispatchEventImpl(Container.java:2317)
    at java.awt.Component.dispatchEvent(Component.java:4793)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
    at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4690)
    at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4668)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4519)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4480)
    at java.awt.Container.dispatchEventImpl(Container.java:2303)
    at java.awt.Window.dispatchEventImpl(Window.java:2758)
    at java.awt.Component.dispatchEvent(Component.java:4793)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:717)
    at java.awt.EventQueue$3.run(EventQueue.java:711)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:99)
    at java.awt.EventQueue$4.run(EventQueue.java:739)
    at java.awt.EventQueue$4.run(EventQueue.java:737)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

link: https://sentry.io/share/issue/973127a468554af3be51a62252676a14/

Additional info: | None
-- | --
App Build | IU-172.4574.11
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version name | IntelliJ IDEA
App Version | 2017.2.6
Is EAP | false
Java version | 9.0.1
Java vm vendor | Oracle Corporation
Last Action |  
OS Name | Linux

**Comment by pirocks** [comment]
This looks like it came form an old plugin version,

**Comment by SingingBush** [comment]
this was prob before this change:
https://github.com/intellij-dlanguage/intellij-dlanguage/commit/5149b71e36a3238f0e175a925fb23530ad483c83

which went live in v1.15.1
