### ISSUE TITLE
NPE in DNamedStubbedPsiElementBase.getName reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#279]
```
java.lang.NullPointerException: null
    at io.github.intellij.dlanguage.psi.impl.DNamedStubbedPsiElementBase.getName(DNamedStubbedPsiElementBase.java:42)
    at io.github.intellij.dlanguage.resolve.processors.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:69)
    at io.github.intellij.dlanguage.resolve.processors.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:81)
    at io.github.intellij.dlanguage.resolve.processors.DNameScopeProcessor.execute(DNameScopeProcessor.kt:40)
    at io.github.intellij.dlanguage.resolve.ScopeProcessorImplUtil.processDeclaration(ScopeProcessorImplUtil.kt:77)
    at io.github.intellij.dlanguage.psi.DlangFile.processDeclarations(DlangFile.java:82)
    at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1103)
    at io.github.intellij.dlanguage.resolve.processors.basic.BasicResolve.findDefinitionNode(BasicResolve.kt:39)
    at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNodeImpl(DResolveUtil.kt:55)
    at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNode(DResolveUtil.kt:37)
    at io.github.intellij.dlanguage.psi.references.DReference.multiResolve(DReference.kt:55)
    at io.github.intellij.dlanguage.psi.references.DReference.resolve(DReference.kt:68)
    at com.intellij.psi.PsiReferenceBase.isReferenceTo(PsiReferenceBase.java:125)
    at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.lambda$execute$0(PsiSearchHelperImpl.java:754)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:138)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:225)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.execute(PsiSearchHelperImpl.java:750)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:247)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:238)
    at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
    at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$5(PsiSearchHelperImpl.java:421)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
    at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:40)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:405)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$2(PsiSearchHelperImpl.java:323)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesConcurrentlyDespiteWriteActions$3(PsiSearchHelperImpl.java:351)
    at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:133)
    at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:222)
    at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:151)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:237)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
link:
https://sentry.io/share/issue/80a002c4b3f5410aa8f5d041bad87e74/

Additional info: | None
-- | --
App Build | IU-172.4343.14
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version name | IntelliJ IDEA
App Version | 2017.2.5
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | GotoDeclaration
OS Name | Mac OS X

**Comment by pirocks** [comment]
Issue fixed
