### ISSUE TITLE
Index out of bounds exception reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#282]
```
java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
    at com.intellij.util.SmartList.get(SmartList.java:66)
    at io.github.intellij.dlanguage.utils.DUtil.getEndOfIdentifierList(DUtil.java:307)
    at io.github.intellij.dlanguage.psi.impl.named.DLanguageModuleDeclarationImpl.getNameIdentifier(DLanguageModuleDeclarationImpl.java:62)
    at io.github.intellij.dlanguage.psi.impl.named.DLanguageModuleDeclarationImpl.getNameIdentifier(DLanguageModuleDeclarationImpl.java:30)
    at com.intellij.codeInspection.NonAsciiCharactersInspection$1.visitElement(NonAsciiCharactersInspection.java:82)
    at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:215)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
    at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:282)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:250)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
    at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
    at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:237)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

sentry link: https://sentry.io/share/issue/452b3e6b4b78426da349a7cdb89e37ad/

Additional info: | In the following file:  module ; import std.stdio;  void main() { 	double yu = 7.0; 	writeln("Edit source/app.d to start your project."); 	thing._blu(); }
-- | --
App Build | IC-172.4343.14
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version name | IntelliJ IDEA
App Version | 2017.2.5
Is EAP | false
Java version | 1.8.0_152
Java vm vendor | Oracle Corporation
Last Action | None
OS Name | Windows 10

**Comment by pirocks** [comment]
Fixed in 3d208b4
