### ISSUE TITLE
Issue with debugger reported by sentry

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#283]
sentry link:https://sentry.io/share/issue/48e5fb2b052f4f15aaf37f8a5f4b1535/

```
java.lang.NullPointerException: null
    at uk.co.cwspencer.gdb.gdbmi.GdbMiValue.toString(GdbMiValue.java:79)
    at java.lang.String.valueOf(String.java:2994)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at uk.co.cwspencer.gdb.gdbmi.GdbMiResult.toString(GdbMiResult.java:56)
    at java.lang.String.valueOf(String.java:2994)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at uk.co.cwspencer.gdb.gdbmi.GdbMiResultRecord.toString(GdbMiResultRecord.java:66)
    at java.lang.String.valueOf(String.java:2994)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at uk.co.cwspencer.ideagdb.debug.GdbDebugProcess.onResultRecordReceived(GdbDebugProcess.java:354)
    at uk.co.cwspencer.gdb.Gdb.handleResultRecord(Gdb.java:434)
    at uk.co.cwspencer.gdb.Gdb.handleRecord(Gdb.java:405)
    at uk.co.cwspencer.gdb.Gdb.runGdb(Gdb.java:320)
    at uk.co.cwspencer.gdb.Gdb.access$000(Gdb.java:43)
    at uk.co.cwspencer.gdb.Gdb$1.run(Gdb.java:88)
    at java.lang.Thread.run(Thread.java:745)
```

Additional info: | i set a break point then clicked on debug
-- | --
App Build | IU-173.3622.25
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version name | IntelliJ IDEA
App Version | 2017.3 EAP
Is EAP | true
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | EditorBackSpace
OS Name | Mac OS X

**Comment by pirocks** [comment]
If your the person reporting this knowing the gdb version would be helpful for reproducing this issue. I will also make a pr that adds this to sentry.

**Comment by andre2007** [comment]
Very likely also solved with https://github.com/intellij-dlanguage/intellij-dlanguage/pull/429
