### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#296]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/407116339/

```
NullPointerException: None
    at io.github.intellij.dlanguage.actions.DFixAction.update(DFixAction.java:38)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:132)
    at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:235)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:180)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:205)
...
(48 additional frame(s) were not displayed)
```

**Comment by pirocks** [comment]
Additional info: | Not sure wha cuased this. Had two projects open, one dub and one non-dub
-- | --
App Build | IC-172.4343.14
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version | 2017.2.5
Dub Version | DUB version 1.3.0, built on Apr 21 2017
Is EAP | false
Java version | 1.8.0_152
Java vm vendor | Oracle Corporation
Last Action | EditorBackSpace
OS Name | Windows 10
Plugin Id | net.masterthought.dlanguage
Plugin Name FallBack | D Language
Plugin Name | None
Plugin Version Fallback | 1.15.2
Plugin Version | None
error.description | None
error.hash | -389155278
error.message | None
error.stacktrace | java.lang.NullPointerException  	at io.github.intellij.dlanguage.actions.DFixAction.update(DFixAction.java:38)  	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:132)  	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:235)  	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:180)  	at com.intellij.openapi.acti...
plugin id | net.masterthought.dlanguage
