### ISSUE TITLE
IOException in uk.co.cwspencer.gdb.Gdb.processWriteQueue

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#308]
https://sentry.io/share/issue/ec5721c813b5480ea39aa10a43d35804/

```
java.io.IOException: Die Pipe wird gerade geschlossen
    at java.io.FileOutputStream.writeBytes(FileOutputStream.java)
    at java.io.FileOutputStream.write(FileOutputStream.java:326)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at uk.co.cwspencer.gdb.Gdb.processWriteQueue(Gdb.java:379)
    at uk.co.cwspencer.gdb.Gdb.access$500(Gdb.java:43)
    at uk.co.cwspencer.gdb.Gdb$6.run(Gdb.java:294)
    at java.lang.Thread.run(Thread.java:745)
```

Additional info: | None
-- | --
App Build | IC-172.4574.11
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version | 2017.2.6
Dub Version | DUB version 1.6.0, built on Nov  1 2017
GDB Version | GNU gdb (GDB) 7.10.1
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | EditorCopy
OS Name | Windows 10
Plugin Id | net.masterthought.dlanguage
Plugin Name FallBack | D Language
Plugin Name | None
Plugin Version Fallback | 1.15.2
Plugin Version | None
error.description | None
error.hash | 1261878800
error.message | Die Pipe wird gerade geschlossen
error.stacktrace | java.io.IOException: Die Pipe wird gerade geschlossen  	at java.io.FileOutputStream.writeBytes(Native Method)  	at java.io.FileOutputStream.write(FileOutputStream.java:326)  	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)  	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)  	at uk.co.cwspencer.gdb.Gdb.processWriteQueue(Gdb.java:379)  	at uk.co.cwspe...
plugin id | net.masterthought.dlanguage

**Comment by pirocks** [comment]
Language was german and `Die Pipe wird gerade geschlossen` means `The pipe is currently closed` according to google translate.

**Comment by SingingBush** [comment]
looks like _Gdb::processWriteQueue()_ could do with a bit of an overhaul, also _runGdb_ method above it. That _OutputStream_ is never actually closed. Try with resources block would be better.

Could whoever picks this up also contribute the same fixes to https://bitbucket.org/spencercw/ideagdb

**Comment by pirocks** [comment]
I have recieved a slightly different, but related exception:

```
java.io.IOException: Stream closed
    at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
    at java.io.OutputStream.write(OutputStream.java:116)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at uk.co.cwspencer.gdb.Gdb.processWriteQueue(Gdb.java:379)
    at uk.co.cwspencer.gdb.Gdb.access$500(Gdb.java:43)
    at uk.co.cwspencer.gdb.Gdb$6.run(Gdb.java:294)
    at java.lang.Thread.run(Thread.java:745)
```

> looks like Gdb::processWriteQueue() could do with a bit of an overhaul, also runGdb method above it. 
> That OutputStream is never actually closed. Try with resources block would be better.

The whole gdb implementation imo needs an overhaul.

**Comment by bamarc** [comment]
The error is saying "the pipe is being closed".
If you need any help translating german just send me a message.

**Comment by SingingBush** [comment]
sentry report May 28th:

IDEA 2020.1.2
Java 11.0.7
plugin version 1.24.1

```
java.io.IOException: The pipe is being closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at uk.co.cwspencer.gdb.Gdb.processWriteQueu...
```

**Comment by SingingBush** [comment]
few recent Sentry reports for "Stream closed" errors:

```
java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at uk.co.cwspencer.gdb.Gdb.processWriteQueue(..
```

**Comment by SingingBush** [comment]
For now I've made the Gdb class a little more defensive. Any new GDB related problems should be picked up in new tickets but ultimately #598 needs to be done and there should be unit tests for the debugger support
