### ISSUE TITLE
ClassCastException: DLanguageImportBindImpl cannot be cast to DLanguageIdentifierChain

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#316]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/411676538/

```
ClassCastException: io.github.intellij.dlanguage.psi.impl.DLanguageImportBindImpl cannot be cast to io.github.intellij.dlanguage.psi.DLanguageIdentifierChain
    at io.github.intellij.dlanguage.psi.references.DReference.addModuleVariants(DReference.kt:132)
    at io.github.intellij.dlanguage.psi.references.DReference.getVariants(DReference.kt:121)
    at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:273)
    at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:137)
    at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:81)
...
(31 additional frame(s) were not displayed)

io.github.intellij.dlanguage.psi.impl.DLanguageImportBindImpl cannot be cast to io.github.intellij.dlanguage.psi.DLanguageIdentifierChain
```

**Comment by pirocks** [comment]
Additional info: | None
-- | --
App Build | IU-172.4574.11
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version | 2017.2.6
Dub Version | DUB version 1.6.0, built on Nov  3 2017
Is EAP | false
Java version | 1.8.0_144
Java vm vendor | Oracle Corporation
Last Action | CodeCompletion
OS Name | Linux
Plugin Id | net.masterthought.dlanguage
Plugin Name FallBack | D Language
Plugin Name | None
Plugin Version Fallback | 1.15.2
Plugin Version | None
