### ISSUE TITLE
KotlinNullPointerException reported by sentry 

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#317]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/412120088/

```
KotlinNullPointerException: None
    at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.updateFromAttribute(DAttributesFinder.kt:193)
    at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.execute(DAttributesFinder.kt:134)
    at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.recurseUpImpl(DAttributesFinder.kt:88)
    at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.recurseUp(DAttributesFinder.kt:81)
    at io.github.intellij.dlanguage.psi.impl.named.DlangSingleImportImpl.isPublic(DlangSingleImportImpl.java:102)
...
(63 additional frame(s) were not displayed)
```

**Comment by pirocks** [comment]
Additional info:NoneApp BuildIC-173.3727.127App Full NameIntelliJ IDEAApp NameIDEAApp Version nameIntelliJ IDEAApp Version2017.3Is EAPfalseJava version1.8.0_152-releaseJava vm vendorJetBrains s.r.oLast Actionio.github.intellij.dlanguage.ProcessDLibsOS NameLinuxPlugin NameNonePlugin VersionNoneerror.descriptionNone

**Comment by pirocks** [comment]
Duplicate of previous issue. Old plugin version.
