### ISSUE TITLE
Throwable: Cannot find element among its parent' children. element: '

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#319]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/412858973/

```
Throwable: Cannot find element among its parent' children. element: 'PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\maths'; parent: 'PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda'; children: [PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\util, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\audio, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\event, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\input, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\maths, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\world, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\system, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\display, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\resource];  file:null
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.getChildIndex(SharedPsiElementImplUtil.java:136)
    at com.intellij.psi.impl.SharedPsiElementImplUtil.getPrevSibling(SharedPsiElementImplUtil.java:124)
    at com.intellij.psi.impl.PsiElementBase.getPrevSibling(PsiElementBase.java:62)
    at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.recurseUpImpl(DAttributesFinder.kt:91)
...
(18 additional frame(s) were not displayed)

Cannot find element among its parent' children. element: 'PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\maths'; parent: 'PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda'; children: [PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\util, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\audio, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\event, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\input, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\maths, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\world, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\system, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\display, PsiDirectory:D:\Gamedev\Projects\2017\LD40\source\decalda\resource];  file:null
```

**Comment by pirocks** [comment]
Additional info: | None
-- | --
App Build | IC-173.3727.127
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version | 2017.3
D Format Version | 0.5.0
DFix Version |  
DScanner Version | v0.4.0
Dub Version | DUB version 1.5.0, built on Oct  9 2017
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | EditorCopy
OS Name | Windows 10
Plugin Id | net.masterthought.dlanguage
Plugin Name FallBack | D Language
Plugin Name | None
Plugin Version Fallback | 1.15.2
Plugin Version | None
