### ISSUE TITLE
IllegalStateException in code folding

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#320]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/412895561/

```
IllegalStateException: None
    at io.github.intellij.dlanguage.psi.impl.named.DlangSingleImportImpl.getImportedModuleName(DlangSingleImportImpl.java:73)
    at io.github.intellij.dlanguage.stubs.types.SingleImportStubElementType.createStub(SingleImportStubElementType.java:38)
    at io.github.intellij.dlanguage.stubs.types.SingleImportStubElementType.createStub(SingleImportStubElementType.java:20)
    at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.createStub(DefaultStubBuilder.java:113)
    at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:88)
...
(79 additional frame(s) were not displayed)
```

**Comment by pirocks** [comment]
Additional info: | None
-- | --
App Build | IC-173.3727.127
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version | 2017.3
D Format Version | 0.5.0
DFix Version |  
DScanner Version | v0.4.0
Dub Version | DUB version 1.5.0, built on Oct  9 2017
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | None
OS Name | Windows 10
Plugin Id | net.masterthought.dlanguage
Plugin Name FallBack | D Language
Plugin Name | None
Plugin Version Fallback | 1.15.2
Plugin Version | None
