### ISSUE TITLE
Logger error in DLangRunDmdState

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#325]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/415099787/

```
Throwable: None
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
    at io.github.intellij.dlanguage.run.DlangRunDmdState.getDmdCommandLine(DlangRunDmdState.java:121)
    at io.github.intellij.dlanguage.run.DlangRunDmdState.startProcess(DlangRunDmdState.java:60)
    at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
    at io.github.intellij.dlanguage.run.DlangRunDmdState.execute(DlangRunDmdState.java:53)
...
(25 additional frame(s) were not displayed)
```

**Comment by pirocks** [comment]
This is caused by no dmd compiler being configured. I see no reason why this needs to be logged as an error.

**Comment by SingingBush** [comment]
the line in _DlangRunDmdState_ that has `LOG.error("No valid D compiler found");` should be changed to a warn.
