### ISSUE TITLE
IllegalStateException: Something went horribly wrong while renaming. 

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#334]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/425114321/

```
IllegalStateException: Something went horribly wrong while renaming. Target nane:base.d ProjectProject '/Users/<removed>/Develop/Projects/<removed>/Prototype/<removed>' <removed> e:null
    at io.github.intellij.dlanguage.psi.impl.named.DlangIdentifierImpl.setName(DlangIdentifierImpl.java:93)
    at io.github.intellij.dlanguage.psi.references.DReference.handleElementRename(DReference.kt:295)
    at com.intellij.refactoring.rename.RenameUtil.rename(RenameUtil.java:267)
    at com.intellij.refactoring.rename.RenameUtil.doRenameGenericNamedElement(RenameUtil.java:224)
    at com.intellij.refactoring.rename.RenamePsiElementProcessor.renameElement(RenamePsiElementProcessor.java:58)
...
(142 additional frame(s) were not displayed)

Something went horribly wrong while renaming. Target nane:base.d ProjectProject '/Users/<removed>/Develop/Projects/<removed>/Prototype/<removed>' <removed> e:null
```

**Comment by pirocks** [comment]
Caused by renaming files, since files are `something.d` but modules are just `something`
