### ISSUE TITLE
AssertionError in folding

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#342]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/428178405/

```
AssertionError: (7,7), text: import , language = Language: D
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:111)
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:92)
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:77)
    at com.intellij.lang.folding.FoldingDescriptor.<init>(FoldingDescriptor.java:64)
    at io.github.intellij.dlanguage.folding.DFoldingBuilder$FoldingVisitor.visitImportDeclaration(DFoldingBuilder.kt:194)
...
(49 additional frame(s) were not displayed)

(7,7), text: import , language = Language: D
```

**Comment by pirocks** [comment]
Fixed in e2ace10
