### ISSUE TITLE
IllegalArgumentException: string:stringLiteral

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#343]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/427876823/

```
IllegalArgumentException: string:stringLiteral
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8512)
    at io.github.intellij.dlanguage.parser.DLangParser.<init>(DLangParser.java:86)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:24)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:423)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
...
(38 additional frame(s) were not displayed)

string:stringLiteral
```

**Comment by pirocks** [comment]
Duplicate of #350
