### ISSUE TITLE
PicoPluginExtensionInitializationException

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#346]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/433151741/

```
ClassNotFoundException: com.siberika.idea.pascal.jps.sdk.PascalCompilerFamily PluginClassLoader[com.siberika.idea.pascal, 1.40] com.intellij.ide.plugins.cl.PluginClassLoader@75a99581
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.siberika.idea.pascal.sdk.FPCSdkType.<init>(FPCSdkType.java:46)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
...
(60 additional frame(s) were not displayed)

NoClassDefFoundError: com/siberika/idea/pascal/jps/sdk/PascalCompilerFamily
    at com.siberika.idea.pascal.sdk.FPCSdkType.<init>(FPCSdkType.java:46)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
...
(58 additional frame(s) were not displayed)

PicoPluginExtensionInitializationException: com/siberika/idea/pascal/jps/sdk/PascalCompilerFamily
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:96)
    at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:246)
    at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:191)
    at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:102)
...
(49 additional frame(s) were not displayed)

com/siberika/idea/pascal/jps/sdk/PascalCompilerFamily
```

**Comment by pirocks** [comment]
Frankly I'm not sure why we got this report/What we are supposed too do about it. Closing until I receive this again, or someone clarifies.
