### ISSUE TITLE
ProcessNotCreatedException: Cannot run program "C:\D\dcd-0.9.1" 

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#347]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/432123048/

```
IOException: CreateProcess error=5, Access is denied
    at java.lang.ProcessImpl.create(ProcessImpl.java)
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
    at java.lang.ProcessImpl.start(ProcessImpl.java:137)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:420)
...
(127 additional frame(s) were not displayed)

IOException: Cannot run program "C:\D\dcd-0.9.1" (in directory "C:\Users\<removed>\Desktop\<removed>"): CreateProcess error=5, Access is denied
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:420)
    at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:387)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionServer.spawnProcess(DCDCompletionServer.java:148)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionServer.restart(DCDCompletionServer.java:236)
...
(124 additional frame(s) were not displayed)

ProcessNotCreatedException: Cannot run program "C:\D\dcd-0.9.1" (in directory "C:\Users\<removed>\Desktop\<removed>"): CreateProcess error=5, Access is denied
    at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:391)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionServer.spawnProcess(DCDCompletionServer.java:148)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionServer.restart(DCDCompletionServer.java:236)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionServer.onSettingsChanged(DCDCompletionServer.java:224)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
...
(122 additional frame(s) were not displayed)

Cannot run program "C:\D\dcd-0.9.1" (in directory "C:\Users\<removed>\Desktop\<removed>"): CreateProcess error=5, Access is denied
```

**Comment by pirocks** [comment]
This seems to be caused by someone specifying the dcd directory instead of the path to the dcd executables.

**Comment by pirocks** [comment]
Ideally we should have a more use-friendly message.

**Comment by Scellow** [comment]
If the reports are sent by people using the plugin, i think it would be better if personal info was removed (user name + project name)

**Comment by pirocks** [comment]
Agreed, however I'm not sure quite how to implement that. I can manually filter what is posted on GitHub but we'll still get information from exception messages on sentry.

**Comment by pirocks** [comment]
I've pushed commits 8ffd55eb5258eb8f6b5d0e8b745c075a139f7a7e and 347d4e2cfd5a4924714e7a2872e739116f578bcd which remove project names and usernames from exception messages/stacktraces etc. I will also go through the previously reported sentry issues and edit out project names and usernames.
