### ISSUE TITLE
IllegalArgumentException: string:dstringLiteral

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#348]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/431991819/

```
IllegalArgumentException: string:dstringLiteral
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8512)
    at io.github.intellij.dlanguage.parser.DLangParser.<init>(DLangParser.java:86)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:24)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:423)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
...
(45 additional frame(s) were not displayed)

string:dstringLiteral
```

**Comment by pirocks** [comment]
Probably related #350.

**Comment by pirocks** [comment]
Duplicate of #350.
