### ISSUE TITLE
NullPointerException in ExecUtil

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#349]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/431671285/

```
NullPointerException: None
    at io.github.intellij.dlanguage.utils.ExecUtil.exec(ExecUtil.java:49)
    at io.github.intellij.dlanguage.utils.ExecUtil.locateExecutable(ExecUtil.java:103)
    at io.github.intellij.dlanguage.utils.ExecUtil.locateExecutableByGuessing(ExecUtil.java:121)
    at io.github.intellij.dlanguage.utils.GuiUtil.lambda$createApplyPathAction$0(GuiUtil.java:118)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
...
(139 additional frame(s) were not displayed)
```

**Comment by pirocks** [comment]
Fixed in #349
