### ISSUE TITLE
NoValidDlangSdkFound

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#355]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/439798503/

```
Throwable: io.github.intellij.dlanguage.run.exception.NoValidDlangSdkFound
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
    at io.github.intellij.dlanguage.run.RunAppRunner.doExecute(RunAppRunner.java:47)
    at com.intellij.execution.runners.GenericProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
    at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
    at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:75)
...
(40 additional frame(s) were not displayed)

io.github.intellij.dlanguage.run.exception.NoValidDlangSdkFound
```

**Comment by pirocks** [comment]
With improvements like the sdk validator. This is no longer an exception which is likely to be thrown.
