### ISSUE TITLE
ProcessNotCreatedException: Cannot run program "/Library/D/dmd/src/dmd": error=13, Permission denied

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#362]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/445861665/

```
IOException: error=13, Permission denied
    at java.lang.UNIXProcess.$$YJP$$forkAndExec(UNIXProcess.java)
    at java.lang.UNIXProcess.forkAndExec(UNIXProcess.java)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
...
(102 additional frame(s) were not displayed)

IOException: Cannot run program "/Library/D/dmd/src/dmd": error=13, Permission denied
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:415)
    at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:382)
    at io.github.intellij.dlanguage.DlangSdkType.getDmdVersion(DlangSdkType.java:390)
    at io.github.intellij.dlanguage.DlangSdkType.suggestSdkName(DlangSdkType.java:136)
...
(98 additional frame(s) were not displayed)

ProcessNotCreatedException: Cannot run program "/Library/D/dmd/src/dmd": error=13, Permission denied
    at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:386)
    at io.github.intellij.dlanguage.DlangSdkType.getDmdVersion(DlangSdkType.java:390)
    at io.github.intellij.dlanguage.DlangSdkType.suggestSdkName(DlangSdkType.java:136)
    at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.createUniqueSdkName(SdkConfigurationUtil.java:269)
    at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.addSdk(ProjectSdksModel.java:281)
...
(96 additional frame(s) were not displayed)

Cannot run program "/Library/D/dmd/src/dmd": error=13, Permission denied
```

**Comment by pirocks** [comment]
Related #398.

**Comment by SingingBush** [comment]
this should be helped by https://github.com/intellij-dlanguage/intellij-dlanguage/commit/85722d94a4796bfe7ffaf7caaae07cf5c6318089
