### ISSUE TITLE
ProcessNotCreatedException: Cannot run program "C:\Users\<removed>\Documents\GitHub\dfmt\dfmt.exe" (in directory "C:\Users\<removed>\...

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#386]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/462297632/

```
IOException: CreateProcess error=1392, The file or directory is corrupted and unreadable
    at java.lang.ProcessImpl.create(ProcessImpl.java)
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
    at java.lang.ProcessImpl.start(ProcessImpl.java:137)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:415)
...
(55 additional frame(s) were not displayed)

IOException: Cannot run program "C:\Users\<removed>\Documents\GitHub\dfmt\dfmt.exe" (in directory "C:\Users\<removed>\Documents\GitHub\<removed>\source"): CreateProcess error=1392, The file or directory is corrupted and unreadable
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:415)
    at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:382)
    at io.github.intellij.dlanguage.actions.DFormatAction.actionPerformed(DFormatAction.java:90)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
...
(52 additional frame(s) were not displayed)

ProcessNotCreatedException: Cannot run program "C:\Users\franc\Documents\GitHub\dfmt\dfmt.exe" (in directory "C:\Users\franc\Documents\GitHub\math-thing5\source"): CreateProcess error=1392, The file or directory is corrupted and unreadable
    at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:386)
    at io.github.intellij.dlanguage.actions.DFormatAction.actionPerformed(DFormatAction.java:90)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:321)
...
(50 additional frame(s) were not displayed)

Cannot run program "C:\Users\<removed>\Documents\GitHub\dfmt\dfmt.exe" (in directory "C:\Users\<removed>\Documents\GitHub\<removed>\source"): CreateProcess error=1392, The file or directory is corrupted and unreadable
```

**Comment by SingingBush** [comment]
the code around paths, especially on Windows, has been improved and merged in develop branch. Any issues like this should be resolved after the 1.26.2 release
