### ISSUE TITLE
NullPointerException in parser

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#389]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/457146182/

```
NullPointerException: None
    at io.github.intellij.dlanguage.parser.DLangParser.currentIsOneOf(DLangParser.java:8587)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8299)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8287)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAndExpression(DLangParser.java:699)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9037)
...
(63 additional frame(s) were not displayed)
```

**Comment by pirocks** [comment]
Fixed in 755b8fcded00d91986c8f6387342569150c57782
