### ISSUE TITLE
DModuleIndex is causing an IndexNotReadyException

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#402]
been getting this stack trace recently on develop branch:

```
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:77)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:753)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:702)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:873)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:959)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:930)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:792)
	at io.github.intellij.dlanguage.index.DModuleIndex.getVirtualFilesByModuleName(DModuleIndex.java:49)
	at io.github.intellij.dlanguage.index.DModuleIndex.getFilesByModuleName(DModuleIndex.java:39)
	at io.github.intellij.dlanguage.resolve.processors.basic.BasicResolve.getObject(BasicResolve.kt:32)
	at io.github.intellij.dlanguage.DLangProjectDmdSetupValidator$cannotFindObjectDotD$resolveObjectDotD$1.compute(DLanguage.kt:100)
	at io.github.intellij.dlanguage.DLangProjectDmdSetupValidator$cannotFindObjectDotD$resolveObjectDotD$1.compute(DLanguage.kt:64)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:79)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:110)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:79)
	at io.github.intellij.dlanguage.DLangProjectDmdSetupValidator.cannotFindObjectDotD(DLanguage.kt:102)
	at io.github.intellij.dlanguage.DLangProjectDmdSetupValidator.isApplicableFor(DLanguage.kt:77)
	at com.intellij.codeInsight.daemon.impl.SdkSetupNotificationProvider.createNotificationPanel(SdkSetupNotificationProvider.java:61)
	at com.intellij.codeInsight.daemon.impl.SdkSetupNotificationProvider.createNotificationPanel(SdkSetupNotificationProvider.java:36)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:235)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:46)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:186)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

need to take a look at _io.github.intellij.dlanguage.index.DModuleIndex_:

```
    @NotNull
    public static Collection<VirtualFile> getVirtualFilesByModuleName(@NotNull final String moduleName,
                                                                      @NotNull final GlobalSearchScope searchScope) {
        return FileBasedIndex.getInstance().getContainingFiles(D_MODULE_INDEX, moduleName, searchScope);
    }
```

**Comment by pirocks** [comment]
I've noticed this and asked around on the forum, but have not received any
response yet. This caused by the project sdk validator acsessing the file
index in order to determine if object.d an dither standard library files
are present.
