### ISSUE TITLE
indexing dub dependencies takes ages

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#417]
I have [gtkd](https://github.com/gtkd-developers/GtkD) in a small project and am finding that it takes ages to index. Not sure if there is anything we can do to make this better

**Comment by pirocks** [comment]
I'm going to be busy for the next two weeks, but after that I should be able to look into this. Can you post your dub.json/sdl.

**Comment by SingingBush** [comment]
this issue and this is probably related to #419 are probably related. When using D tools we need to make sure we're using `ApplicationManager.getApplication().executeOnPooledThread()` and `ApplicationManager.getApplication().invokeLater()` were applicable. 

It's worth referring to [How to create a background task in IntelliJ plugin](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206119459-How-to-create-a-background-task-in-IntelliJ-plugin).  eg:

```java
ApplicationManager.getApplication().executeOnPooledThread(new Runnable() {
    public void run() {
        ApplicationManager.getApplication().runReadAction(new Runnable() {
            public void run() {
                // do whatever you need to do
            }
        });
    }
});
```

the `io.github.intellij.dlanguage.project.DubConfigurationParser` class is a major problem as `dub describe` can take ages. The DubConfigurationParser is also used by DCD.

**Comment by SingingBush** [comment]
this is still a problem. There are sentry reports for:

```
java.util.concurrent.TimeoutException
 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
 	at io.github.intellij.dlanguage.project.DubConfigurationParser.getDubProject(DubConfigurationParser.java:79)
 	at io.github.intellij.dlanguage.project.DubConfigurationParser.getDubPackageDependencies(DubConfigurationParser.java:126)
 	at io.github.intellij.dlanguage.actions.ProcessDLi...
```

**Comment by SingingBush** [comment]
still getting reports of timeout exceptions:

```
java.util.concurrent.TimeoutException 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
 	at io.github.intellij.dlanguage.project.DubConfigurationParser.getDubProject(DubConfigurationParser.java:79)
 	at io.github.intellij.dlanguage.project.DubProjectImportBuilder.buildModules(DubProjectImportBuilder.java:135)
 	at io.github.intellij.dlanguage.project.DubProjectImportBuild...
```

```
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.github.intellij.dlanguage.project.DubConfigurationParser.getDubProject(DubConfigurationParser.java:79)
	at io.github.intellij.dlanguage.project.DubProjectImportBuilder.buildModules(DubProjectImportBuilder.java:135)
	at io.github.intellij.dlanguage.project.DubProjectImportBuild...
```

the last actions were: opening IDE, EditorBackSpace, CloseProject, OpenFile
