### ISSUE TITLE
Windows Debugging using MagoMI: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#427]
While debugging on Windows using MagoMI there is an ArrayIndexOutOfBoundsException here
https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/java/uk/co/cwspencer/gdb/gdbmi/GdbMiParser2.java#L64

java.lang.ArrayIndexOutOfBoundsException: 0
	at uk.co.cwspencer.gdb.gdbmi.GdbMiParser2.parseBreakpointHitLineFrameLine(GdbMiParser2.java:64)
	at uk.co.cwspencer.gdb.gdbmi.GdbMiParser2.parseBreakpointHitLine(GdbMiParser2.java:1204)
	at uk.co.cwspencer.gdb.gdbmi.GdbMiParser2.parseExecLine(GdbMiParser2.java:667)
	at uk.co.cwspencer.gdb.gdbmi.GdbMiParser2.parseLine(GdbMiParser2.java:582)
	at uk.co.cwspencer.gdb.gdbmi.GdbMiParser2.process(GdbMiParser2.java:481)
	at uk.co.cwspencer.gdb.Gdb.runGdb(Gdb.java:309)
	at uk.co.cwspencer.gdb.Gdb.access$000(Gdb.java:43)
	at uk.co.cwspencer.gdb.Gdb$1.run(Gdb.java:88)
	at java.lang.Thread.run(Thread.java:745)

Variable line has content: {addr="0x00402279",func="D main+0x1d",args=[],file="C:\\D\\projects\\magotest\\source\\app.d",fullname="C:\\D\\projects\\magotest\\source\\app.d",line="6",from="C:\\D\\projects\\magotest\\magotest.exe"}

**Comment by andre2007** [comment]
It seems the root cause of the exception is the missing "level" value in variable line.
The regular expression built in method parseFrameLine
 ```\{(?:level="(\d+)")?,?(?:addr="([^"]+)")?,?(?:func="([^"]+)")?,?(?:args=\[(.*?)\])?,(?:file="([^"]+)")?,?(?:fullname="([^"]+)")?,?(?:line="(\d+)")?\}``` 

does not match to line variable

 ```{addr="0x00402279",func="D main+0x1d",args=[],file="C:\D\projects\magotest\source\app.d",fullname="C:\D\projects\magotest\source\app.d",line="6",from="C:\D\projects\magotest\magotest.exe"}```

MagoMI has the level value and depending on the situation it is added to the frameLine. For this situation (line break hit) it is not added.

https://github.com/rainers/mago/search?q=dumpMIFrame&unscoped_q=dumpMIFrame

**Comment by andre2007** [comment]
I did some more investigations. It seems MagoMI is running fine in IDE DlangUI.
Here I found following behavior.

1.) breakpoint-hit also here does not contain a "level" attribute. 

2.) after "breakpoint-hit" the command "-thread-info" is executed. 
Example output:
```
^done,threads=[{id="4824",target-id="4824",frame={addr="0x7756bebc",from="C:\\Windows\\SysWOW64\\ntdll.dll"},state="stopped"},{id="5732",target-id="5732",frame={addr="0x00402279",func="D main+0x1d",args=[],file="C:\\D\\projects\\magotest\\source\\app.d",fullname="C:\\D\\projects\\magotest\\source\\app.d",line="6",from="C:\\D\\projects\\magotest\\magotest.exe"},state="stopped"},{id="10776",target-id="10776",frame={addr="0x7756bebc",from="C:\\Windows\\SysWOW64\\ntdll.dll"},state="stopped"},{id="11228",target-id="11228",frame={addr="0x7756bebc",from="C:\\Windows\\SysWOW64\\ntdll.dll"},state="stopped"}],current-thread-id="5732"
```
This command is executed to find out the thread id "5732"

3.) Command "-stack-list-frames --thread 5732" is executed. Here the frame now contains the level:

```
^done,stack=[frame={level="0",addr="0x00402279",func="D main+0x1d",args=[],file="C:\\D\\projects\\magotest\\source\\app.d",fullname="C:\\D\\projects\\magotest\\source\\app.d",line="6",from="C:\\D\\projects\\magotest\\magotest.exe"},frame={level="1",addr="0x0040299b",func="__D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv+0x1b",args=[],from="C:\\D\\projects\\magotest\\magotest.exe"},frame={level="2",addr="0x0040291d",func="__D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZv+0x89",args=[],from="C:\\D\\projects\\magotest\\magotest.exe"},frame={level="3",addr="0x004027b8",func="__d_run_main+0x1f8",args=[],from="C:\\D\\projects\\magotest\\magotest.exe"},frame={level="4",addr="0x004025b0",func="__entrypoint.main+0x14",args=[],file="C:\\D\\projects\\magotest\\source\\app.d",fullname="C:\\D\\projects\\magotest\\source\\app.d",line="7",from="C:\\D\\projects\\magotest\\magotest.exe"},frame={level="5",addr="0x004244c9",func="_mainCRTStartup+0xa9",args=[],from="C:\\D\\projects\\magotest\\magotest.exe"},frame={level="6",addr="0x77328484",from="C:\\Windows\\SysWOW64\\kernel32.dll"},frame={level="7",addr="0x77562fea",from="C:\\Windows\\SysWOW64\\ntdll.dll"},frame={level="8",addr="0x77562fba",from="C:\\Windows\\SysWOW64\\ntdll.dll"}]
```

I also tried GDB MI under linux and had the exact same behavior like MagoMI. It seems the bug is in the GDBMI library within IntelliJ D plugin. Not the frame from the debug point should be analyzed for level but the frame from command -stack-list-frames
