### ISSUE TITLE
KotlinNullPointerException

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#437]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/588367297/

```
KotlinNullPointerException: None
    at io.github.intellij.dlanguage.resolve.ScopeProcessorImpl.processDeclarations(ScopeProcessorImpl.kt:470)
    at io.github.intellij.dlanguage.psi.impl.named.DLanguageConstructorImpl.processDeclarations(DLanguageConstructorImpl.java:145)
    at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1120)
    at io.github.intellij.dlanguage.resolve.processors.basic.BasicResolve.findDefinitionNode(BasicResolve.kt:42)
    at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNodeImpl(DResolveUtil.kt:55)
...
(35 additional frame(s) were not displayed)
```

**Comment by SingingBush** [comment]
the line in the Kotlin file with the problem had `element.parameters!!` while the Java for the parameters is annotated as being nullable:

```java
@Nullable
DLanguageParameters getParameters();
```

I've ammended the Kotlin code to be:

```kotlin
element.parameters?.let {
    if (!processParameters(it, processor, state, lastParent, place)) {
        return false
    }
}
```
