### ISSUE TITLE
NoSuchMethodError: com.intellij.configurationStore.StorageUtilKt.getNOTIFICATION_GROUP_ID()Ljava/lang/String;

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#438]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/584480511/

```
NoSuchMethodError: com.intellij.configurationStore.StorageUtilKt.getNOTIFICATION_GROUP_ID()Ljava/lang/String;
    at io.github.intellij.dlanguage.features.formatter.DFormattingModelBuilder$DFormattingBlock.getSpacing(DFormattingModelBuilder.kt:188)
    at com.intellij.formatting.InitialInfoBuilder.initCurrentWhiteSpace(InitialInfoBuilder.java:290)
    at com.intellij.formatting.InitialInfoBuilder.doIteration(InitialInfoBuilder.java:262)
    at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:136)
    at com.intellij.formatting.engine.WrapBlocksState.doIteration(WrapBlocksState.java:47)
...
(61 additional frame(s) were not displayed)

com.intellij.configurationStore.StorageUtilKt.getNOTIFICATION_GROUP_ID()Ljava/lang/String;
```

**Comment by SingingBush** [comment]
any chance of getting the IDE type and version for this?

**Comment by pirocks** [comment]
Additional info: | None
-- | --
App Build | IU-181.4892.42
App Full Name | IntelliJ IDEA
App Name | IDEA
App Version | 2018.1.3
D Format Version | 0.7.0
DScanner Version | v0.5.4
Dub Version | DUB version 1.9.0, built on May  2 2018
GDB Version | GNU gdb (GDB) 8.1
Is EAP | false
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | None
OS Name | Mac OS X
Plugin Id | net.masterthought.dlanguage
Plugin Name | None
Plugin Name FallBack | D Language
Plugin Version | None
Plugin Version Fallback | 1.16.2

**Comment by pirocks** [comment]
This is the only one report I can see in sentry.

**Comment by SingingBush** [comment]
This was likely something to do with a mismatch in Kotlin versions. It's an older Intellij release so closing ticket as there have not been any other Sentry reports like this
