### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#440]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/579637937/

```
StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1967)
    at io.github.intellij.dlanguage.run.DubBuildSourceFileFilter.applyFilter(DubBuildStackTraceFilter.kt:22)
    at com.intellij.terminal.JBTerminalWidget$3.apply(JBTerminalWidget.java:203)
    at com.jediterm.terminal.model.hyperlinks.TextProcessing.processHyperlinks(TextProcessing.java:28)
    at com.jediterm.terminal.model.LinesBuffer.lambda$writeString$0(LinesBuffer.java:152)
...
(17 additional frame(s) were not displayed)

String index out of range: -1
```

**Comment by SingingBush** [comment]
the code didn't consider fact that _indexOf_ can return `-1` which was then being used in a _substring_, doh!
