### ISSUE TITLE
IllegalArgumentException: string:intLiteral

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#441]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/575540876/

```
IllegalArgumentException: string:intLiteral
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8560)
    at io.github.intellij.dlanguage.parser.DLangParser.parseVersionCondition(DLangParser.java:7925)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCompileCondition(DLangParser.java:2282)
    at io.github.intellij.dlanguage.parser.DLangParser.parseConditionalDeclaration(DLangParser.java:2325)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:2926)
...
(44 additional frame(s) were not displayed)

string:intLiteral
```

**Comment by SingingBush** [comment]
should be fixed by recent changes to DLangParser in #558
