### ISSUE TITLE
NullPointerException in currentIsOneOf

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#442]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/572424845/

```
NullPointerException: None
    at io.github.intellij.dlanguage.parser.DLangParser.currentIsOneOf(DLangParser.java:8570)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAssignExpression(DLangParser.java:1525)
    at io.github.intellij.dlanguage.parser.DLangParser.parseEnumMember(DLangParser.java:3466)
    at io.github.intellij.dlanguage.parser.DLangParser.parseEnumBody(DLangParser.java:3285)
    at io.github.intellij.dlanguage.parser.DLangParser.parseEnumDeclaration(DLangParser.java:3442)
...
(43 additional frame(s) were not displayed)
```

**Comment by SingingBush** [comment]
Haven't looked into root cause but for now just added null check in DLangParser::currentIsOneOf
