### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#443]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/568589145/

```
IllegalStateException: None
    at io.github.intellij.dlanguage.stubs.DlangSingleImportStub.<init>(DlangSingleImportStub.java:32)
    at io.github.intellij.dlanguage.stubs.types.SingleImportStubElementType.createStub(SingleImportStubElementType.java:42)
    at io.github.intellij.dlanguage.stubs.types.SingleImportStubElementType.createStub(SingleImportStubElementType.java:20)
    at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.createStub(DefaultStubBuilder.java:113)
    at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:88)
...
(81 additional frame(s) were not displayed)
```

**Comment by SingingBush** [comment]
code in question `io.github.intellij.dlanguage.stubs.DlangSingleImportStub`:

```java
    public DlangSingleImportStub(final StubElement parent, final IStubElementType elementType,
        final String name, final int numBinds, final Set<StringRef> binds,
        final @NotNull String importedModule, final boolean hasName, final String importName,
        final DAttributes attributes) {
        super(parent, elementType, name, attributes);
        this.numBinds = numBinds;
        for (final StringRef bind : binds) {
            this.binds.add(bind.getString());
        }
        this.importedModule = importedModule;
        if (importedModule.equals(""))
            throw new IllegalStateException();       <---   so the imported module was an empty string
        this.hasName = hasName;
        this.importName = importName;
    }
```
