### ISSUE TITLE
IllegalArgumentException: string:characterLiteral

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#445]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/539253062/

```
IllegalArgumentException: string:characterLiteral
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8560)
    at io.github.intellij.dlanguage.parser.DLangParser.<init>(DLangParser.java:91)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:24)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:423)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
...
(52 additional frame(s) were not displayed)

string:characterLiteral
```

**Comment by SingingBush** [comment]
still an issue now:

```
java.lang.IllegalArgumentException: string:characterLiteral
	at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8560)
	at io.github.intellij.dlanguage.parser.DLangParser.<init>(DLangParser.java:91)
	at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:24)
	at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:423)
	at co...
```

should now be fixed by changes in #558
