### ISSUE TITLE
NoClassDefFoundError: com/intellij/psi/util/PsiUtil

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#446]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/535958449/

```
NoClassDefFoundError: com/intellij/psi/util/PsiUtil
    at io.github.intellij.dlanguage.DlangIconProvider.getIcon(icons.kt:15)
    at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
    at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:101)
    at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:45)
    at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:278)
...
(19 additional frame(s) were not displayed)

com/intellij/psi/util/PsiUtil
```

**Comment by pirocks** [comment]
Reproduced. Can be triggered , by creating a clion project, without sdk, and then opening the generated main d file.

**Comment by SingingBush** [comment]
just noticed this after creating #468, will close this and keep the newer issue open
