### ISSUE TITLE
IllegalArgumentException: string:wstringLiteral

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#447]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/535264498/

```
IllegalArgumentException: string:wstringLiteral
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8529)
    at io.github.intellij.dlanguage.parser.DLangParser.<init>(DLangParser.java:86)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:24)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:423)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
...
(42 additional frame(s) were not displayed)

string:wstringLiteral
```

**Comment by SingingBush** [comment]
should be resolved by recent changes in #558
