### ISSUE TITLE
ProcessDLibs cannot handle sub packages

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#474]
dub.json contains sub package specification:

```json
"dependencies" : {
 "arsd-official:cgi" : "2.1.0"
 }
```

During action ProcessDLibs this cause the error:

```
java.lang.Throwable: error while fetching:Package arsd-official:cgi not found for registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): (1): Error: Got JSON of type null_, expected object.

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.getSourcesVirtualFile(ProcessDLibs.kt:268)
	at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.createLibraryDependency(ProcessDLibs.kt:181)
	at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.processDLibsImpl(ProcessDLibs.kt:139)
	at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.access$processDLibsImpl(ProcessDLibs.kt:76)
	at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion$processDLibs$1$task$1.run(ProcessDLibs.kt:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by andre2007** [comment]
The issue is, dub fetch doesn't support the format packageName:subPackageName
This fails:
```dub fetch arsd-official:cgi```

dub fetch is called here
https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/kotlin/io/github/intellij/dlanguage/actions/ProcessDLibs.kt#L237

Maybe in case ```dubPackage.name``` contains a sub package, only the parent package is passed to dub fetch.

I will also check whether dub fetch can be enhanced, but that is nothing the IntelliJ plugin can rely on.

**Comment by SingingBush** [comment]
Sentry report for this:

```
java.lang.Throwable: error while fetching:Package ann_exec:testsuite not found for registry at https://code.dlang.org/ (fallbacks registry at https://code-mirror.dlang.io/, registry at https://dub-registry.herokuapp.com/): (1): Error: Got JSON of type null_, expected object.

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at io.github.intellij.dlanguage.actions.ProcessDLi...
```

last action was ShowSettings
