### ISSUE TITLE
error in DlangModuleBuilder on v1.22 on Clion 2019.3

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#541]
last action was _WelcomeScreen.OpenProject_

```
com.intellij.diagnostic.PluginException: While loading class io.github.intellij.dlanguage.module.DlangModuleBuilder$1: com/intellij/ide/util/projectWizard/ProjectJdkForModuleStep [Plugin: net.masterthought.dlanguage]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:223)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoade...
```

**Comment by SingingBush** [comment]
Seen this again in sentry on CLion 2020.1.2 with plugin version 1.24.1:

```
com.intellij.diagnostic.PluginException: While loading class io.github.intellij.dlanguage.module.DlangModuleBuilder$1: com/intellij/ide/util/projectWizard/ProjectJdkForModuleStep [Plugin: net.masterthought.dlanguage]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoade...
```

last action: _WelcomeScreen.OpenProject_

**Comment by SingingBush** [comment]
*last action* WelcomeScreen.OpenProject

```
com.intellij.diagnostic.PluginException: While loading class io.github.intellij.dlanguage.module.DlangModuleBuilder$1: com/intellij/ide/util/projectWizard/ProjectJdkForModuleStep [Plugin: net.masterthought.dlanguage]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoa...
```

**Comment by xdrie** [comment]
I am also seeing this error.

**Comment by SingingBush** [comment]
This happens when opening a project via _File_ -> _Open_

start looking in _io.github.intellij.dlanguage.project.CLionDubProjectOpenProcessor::doOpenProject()_ which makes a DlangModuleBuilder

**Comment by SingingBush** [comment]
Windows 10
IDE: *CLion 2020.3.3*
plugin: *v1.26*

Last Action *WelcomeScreen.OpenDirectoryProject*

```
java.lang.ClassNotFoundException: com.intellij.ide.util.projectWizard.ProjectJdkForModuleStep PluginClassLoader[PluginDescriptor(name=D Language, id=net.masterthought.dlanguage, path=C:\Users\USERNAME\AppData\Roaming\JetBrains\CLion2020.3\plugins\intellij-dlanguage, version=1.26)] com.intellij.ide.plugins.cl.PluginClassLoader@639292d4
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at java.lang.ClassLoader.defineClass1(ClassLoader.java)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:404)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:389)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:350)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:315)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:238)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:127)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at io.github.intellij.dlanguage.project.CLionDubProjectOpenProcessor.lambda$doOpenProject$0(CLionDubProjectOpenProcessor.java:83)
    at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
    at io.github.intellij.dlanguage.project.CLionDubProjectOpenProcessor.doOpenProject(CLionDubProjectOpenProcessor.java:80)
    at com.intellij.ide.impl.ProjectUtil.lambda$chooseProcessorAndOpen$7(ProjectUtil.java:255)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:463)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:481)
    at com.intellij.ide.impl.ProjectUtil.chooseProcessorAndOpen(ProjectUtil.java:254)
    at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:211)
    at com.intellij.ide.actions.OpenFileAction.openExistingDir(OpenFileAction.java:159)
    at com.intellij.ide.actions.OpenFileAction.doOpenFile(OpenFileAction.java:112)
    at com.intellij.ide.actions.OpenFileAction.lambda$actionPerformed$0(OpenFileAction.java:73)
    at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:146)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:101)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:79)
    at com.intellij.ide.actions.OpenFileAction.actionPerformed(OpenFileAction.java:64)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:275)
    at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.performAnActionForComponent(WelcomeScreenActionsUtil.java:99)
    at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil$LargeIconWithTextWrapper.lambda$new$0(WelcomeScreenActionsUtil.java:128)
```
