### ISSUE TITLE
ClassNotFoundException: com.intellij.ide.plugins.PluginManager

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#545]
IDEA Community Edition 2019.3 on Linux:

```
java.lang.ClassNotFoundException: com.intellij.ide.plugins.PluginManager
    at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
    at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Comment by SingingBush** [comment]
Closing this as not much to on on. Is possibly related to #541
