### ISSUE TITLE
RuntimeException in DubBuildSourceFileFilter

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#546]
Reported from v1.22 running in PyCharm 2019.2.5 on Linux but may well be issue on other ide's:

```
java.lang.RuntimeException: Error while applying io.github.intellij.dlanguage.run.DubBuildSourceFileFilter@417a9ab to 'source_filename = "sum"'
	at com.intellij.terminal.JBTerminalWidget.lambda$addMessageFilter$17(JBTerminalWidget.java:257)
	at com.jediterm.terminal.model.hyperlinks.TextProcessing.doProcessHyperlinks(TextProcessing.java:67)
	at com.jediterm.terminal.model.hyperlinks.TextProcess...
```

**Comment by SingingBush** [comment]
Same again:

IDEA 2019.3.3
JDK 11.0.5
plugin 1.22
**last action**: SaveAll

```
ava.lang.RuntimeException: java.lang.RuntimeException: Error while applying io.github.intellij.dlanguage.run.DubBuildSourceFileFilter@1accc482 to 'source/app.d:13 _Dmain [0x561245ef1833]
'
	at com.intellij.execution.impl.AsyncFilterRunner.isQuick(AsyncFilterRunner.java:83)
	at com.intellij.execution.impl.AsyncFilterRunner.highlightHyperlinks(AsyncFilterRunner.java:62)
	at com.intellij.executio...
```

**Comment by SingingBush** [comment]
| prop| val |
| --- | --- |
| Plugin | 1.25 |
| IDE | Intellij 2020.2.1 |
| Last Action | $Undo |


```
java.lang.RuntimeException: Error while applying io.github.intellij.dlanguage.run.DubBuildSourceFileFilter@e0d43a1 to 'source/app.d(62): [unittest] assertThrown failed: No Exception was thrown.'
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:83)
	at com.intellij.terminal.JBTerminalWidget.lambda$runFilters$1(JBTerminalWidget.java:87)
	at com.intellij.openapi....
```
