### ISSUE TITLE
ProcessNotCreatedException when running various D Tools

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#550]
seems that it's still possible to attempt running dub without a valid path. Not sure where as generally this has been checked before attempting to start the process. 

App Name | IDEA
-- | --
App Version | 2019.3.1
Java version | 11.0.5
Java vm vendor | JetBrains s.r.o
OS Name | Linux

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/bin/dub": error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:424)
	at io.github.intellij.dlanguage.utils.ExecUtil.lambda$readCommandLine$0(ExecUtil.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(Applica...
```

**Comment by SingingBush** [comment]
similar errors reported by Windows users

**Comment by SingingBush** [comment]
more of the same:

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/bin/dub": error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:424)
	at io.github.intellij.dlanguage.utils.ExecUtil.lambda$readCommandLine$0(ExecUtil.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(Applica.
```

**Comment by SingingBush** [comment]
same issue for dscanner:

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/local/bin/dscanner": error=2, Нет такого файла или каталога
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:424)
	at io.github.intellij.dlanguage.utils.ExecUtil.lambda$readCommandLine$0(ExecUtil.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl...
```

**Comment by SingingBush** [comment]
similar issue but shows dub and dscanner:

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "dub dscanner": error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:418)
	at io.github.intellij.dlanguage.utils.ExecUtil.lambda$readCommandLine$0(ExecUtil.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(Applica...
```

last action was *CompileDirty*

**Comment by SingingBush** [comment]
IntelliJ IDEA Ultimate Edition 2019.3.3
D plugin: v1.24.1

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/local/bin/dscanner": error=2, Нет такого файла или каталога
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:424)
	at io.github.intellij.dlanguage.utils.ExecUtil.lambda$readCommandLine$0(ExecUtil.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl...
```

**Comment by SingingBush** [comment]
Sentry report for this:

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/usr/local/bin/dub" (in directory "/Users/wj008/work/dlang/rmdb"): error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:426)
	at io.github.intellij.dlanguage.project.DubConfigurationParser.parseDubConfiguration(DubConfigurationParser.jav...
```

**Comment by SingingBush** [comment]
Still a problem in develop branch. Got following stack trace when attempting to create new D (dub based) project:

```
java.lang.Throwable: Synchronous execution on EDT: \D\dmd2\windows\bin\dub.exe init -n --format json --type minimal, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:171)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:109)
	at io.github.intellij.dlanguage.module.DlangDubModuleBuilder.createDub(DlangDubModuleBuilder.java:130)
	at io.github.intellij.dlanguage.module.DlangDubModuleBuilder.getSourcePaths(DlangDubModuleBuilder.java:85)
	at io.github.intellij.dlanguage.module.DlangModuleBuilder.setupRootModel(DlangModuleBuilder.java:104)
	at io.github.intellij.dlanguage.module.DlangDubModuleBuilder.setupRootModel(DlangDubModuleBuilder.java:54)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.setupModule(ModuleBuilder.java:260)
```

**Comment by SingingBush** [comment]
plugin version 1.25:


Additional info: | null
-- | --
error.message | "Cannot run program \"V:\\Delo\\D_lang\\from_github\\dfmt\\bin\": CreateProcess error=5, Access is denied"
error.stacktrace | "com.intellij.execution.process.ProcessNotCreatedException: Cannot run program \"V:\\Delo\\D_lang\\from_github\\dfmt\\bin\": CreateProcess error=5, Access is denied\r\n\tat com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:380)\r\n\tat io.github.intellij.dlanguage.utils.ExecUtil.lambda$readCommandLine$0(ExecUtil.java:163)\r\n\tat com.intellij.openapi.application.impl..."
Last Action | null

should be sorted already

**Comment by SingingBush** [comment]
I've put in some tweaks to prevent many of the errors in this ticket although I didn't do anything to handle "Access is denied". That perhaps needs to be another ticket.
