### ISSUE TITLE
ClassCastException: PsiFileStubImpl cannot be cast to DlangFileStub

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#552]
```
java.lang.ClassCastException: class com.intellij.psi.stubs.PsiFileStubImpl cannot be cast to class io.github.intellij.dlanguage.stubs.DlangFileStub (com.intellij.psi.stubs.PsiFileStubImpl is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @569cfc36; io.github.intellij.dlanguage.stubs.DlangFileStub is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader
```

**Comment by SingingBush** [comment]
this is in numerous bug reports now:

```
java.lang.ClassCastException: class com.intellij.psi.stubs.PsiFileStubImpl cannot be cast to class io.github.intellij.dlanguage.stubs.DlangFileStub (com.intellij.psi.stubs.PsiFileStubImpl is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @59494225; io.github.intellij.dlanguage.stubs.DlangFileStub is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader
```

**Comment by SingingBush** [comment]
plugin version 1.26.1 on Intellij IDEA 2021.2:

```
java.lang.ClassCastException: class com.intellij.psi.stubs.PsiFileStubImpl cannot be cast to class io.github.intellij.dlanguage.stubs.DlangFileStub (com.intellij.psi.stubs.PsiFileStubImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @6536e911; io.github.intellij.dlanguage.stubs.DlangFileStub is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @368ccf87)
    at io.github.intellij.dlanguage.psi.DlangFile.getStub(DlangFile.java:97)
    at io.github.intellij.dlanguage.psi.DlangFile.getStub(DlangFile.java:28)
    at org.jetbrains.plugins.scala.lang.psi.ScalaPsiUtil$.stub(ScalaPsiUtil.scala:526)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.$anonfun$unapply$1(ImplicitUtil.scala:148)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.$anonfun$unapply$1$adapted(ImplicitUtil.scala:148)
    at org.jetbrains.plugins.scala.extensions.NullSafe$.exists$extension(NullSafe.scala:41)
    at org.jetbrains.plugins.scala.extensions.NullSafe$.withFilter$extension(NullSafe.scala:53)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.unapply(ImplicitUtil.scala:148)
    at org.jetbrains.plugins.scala.findUsages.factory.ScalaFindUsagesHandlerFactory.canFindUsages(ScalaFindUsagesHandlerFactory.scala:43)
    at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:170)
    at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:164)
    at com.intellij.codeInsight.highlighting.HighlightUsagesKt.getPsiUsageRanges(highlightUsages.kt:84)
    at com.intellij.codeInsight.highlighting.HighlightUsagesKt.getUsageRanges(highlightUsages.kt:56)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.lambda$highlightTargetUsages$0(IdentifierHighlighterPass.java:213)
    at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:172)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:212)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:188)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
    at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$updateHighlighted$1(BackgroundHighlighter.java:150)
    at com.intellij.codeInsight.highlighting.BackgroundHighlightingUtil.lambda$lookForInjectedFileInOtherThread$0(BackgroundHighlightingUtil.java:54)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by SingingBush** [comment]
reported from v1.27 on Intellij 2021.3 on Linux:

```
java.lang.ClassCastException: class com.intellij.psi.stubs.PsiFileStubImpl cannot be cast to class io.github.intellij.dlanguage.stubs.DlangFileStub (com.intellij.psi.stubs.PsiFileStubImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @59fa1d9b; io.github.intellij.dlanguage.stubs.DlangFileStub is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @46fd1e1d)
    at io.github.intellij.dlanguage.psi.DlangFile.getStub(DlangFile.java:97)
    at io.github.intellij.dlanguage.psi.DlangFile.getStub(DlangFile.java:28)
    at org.jetbrains.plugins.scala.lang.psi.ScalaPsiUtil$.stub(ScalaPsiUtil.scala:528)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.$anonfun$unapply$1(ImplicitUtil.scala:148)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.$anonfun$unapply$1$adapted(ImplicitUtil.scala:147)
    at org.jetbrains.plugins.scala.extensions.NullSafe$.exists$extension(NullSafe.scala:41)
    at org.jetbrains.plugins.scala.extensions.NullSafe$.withFilter$extension(NullSafe.scala:53)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.unapply(ImplicitUtil.scala:147)
    at org.jetbrains.plugins.scala.findUsages.factory.ScalaFindUsagesHandlerFactory.canFindUsages(ScalaFindUsagesHandlerFactory.scala:44)
    at com.intellij.find.findUsages.FindUsagesManager.canFindUsages(FindUsagesManager.java:91)
    at com.intellij.find.impl.FindManagerImpl.canFindUsages(FindManagerImpl.java:901)
    at com.intellij.find.findUsages.DefaultUsageTargetProvider.getTargets(DefaultUsageTargetProvider.java:16)
    at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:51)
    at com.intellij.usages.UsageTargetUtil.findUsageTargets(UsageTargetUtil.java:32)
    at com.intellij.ide.impl.dataRules.UsageTargetsRule.getData(UsageTargetsRule.java:13)
    at com.intellij.ide.impl.DataManagerImpl.getRulesData(DataManagerImpl.java:139)
    at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRule$4(DataManagerImpl.java:127)
    at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:77)
    at com.intellij.openapi.actionSystem.impl.PreCachedDataContext2.getData(PreCachedDataContext2.java:170)
    at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:42)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.ensureSlowDataKeysPreCached(ActionUpdater.java:368)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:127)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:109)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:588)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:434)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$21(ActionUpdater.java:413)
    at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1454)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:413)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:489)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$21(ActionUpdater.java:413)
    at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1454)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:413)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:233)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$13(ActionUpdater.java:286)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$15(ActionUpdater.java:309)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$16(ActionUpdater.java:309)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$17(ActionUpdater.java:305)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:277)
    at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupAsync$18(ActionUpdater.java:304)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:829)
```

need to either change `DlangFile::getStub` or add jvm args to open relevant packages

**Comment by SingingBush** [comment]
reported from v1.27.2 on Intellij 2021.3.2

```
ava.lang.ClassCastException: class com.intellij.psi.stubs.PsiFileStubImpl cannot be cast to class io.github.intellij.dlanguage.stubs.DlangFileStub (com.intellij.psi.stubs.PsiFileStubImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @76f2b07d; io.github.intellij.dlanguage.stubs.DlangFileStub is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6dc5dff3)
    at io.github.intellij.dlanguage.psi.DlangFile.getStub(DlangFile.java:133)
    at io.github.intellij.dlanguage.psi.DlangFile.getStub(DlangFile.java:28)
    at org.jetbrains.plugins.scala.lang.psi.ScalaPsiUtil$.stub(ScalaPsiUtil.scala:528)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.$anonfun$unapply$1(ImplicitUtil.scala:148)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.$anonfun$unapply$1$adapted(ImplicitUtil.scala:147)
    at org.jetbrains.plugins.scala.extensions.NullSafe$.exists$extension(NullSafe.scala:41)
    at org.jetbrains.plugins.scala.extensions.NullSafe$.withFilter$extension(NullSafe.scala:53)
    at org.jetbrains.plugins.scala.util.ImplicitUtil$contextBoundElement$.unapply(ImplicitUtil.scala:147)
    at org.jetbrains.plugins.scala.findUsages.factory.ScalaFindUsagesHandlerFactory.canFindUsages(ScalaFindUsagesHandlerFactory.scala:44)
    at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:160)
    at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:154)
    at com.intellij.codeInsight.highlighting.HighlightUsagesKt.getPsiUsageRanges(highlightUsages.kt:84)
    at com.intellij.codeInsight.highlighting.HighlightUsagesKt.getUsageRanges(highlightUsages.kt:56)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.lambda$highlightTargetUsages$0(IdentifierHighlighterPass.java:213)
    at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:172)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
    at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:212)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:188)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
    at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$updateHighlighted$1(BackgroundHighlighter.java:150)
    at com.intellij.codeInsight.highlighting.BackgroundHighlightingUtil.lambda$lookForInjectedFileInOtherThread$0(BackgroundHighlightingUtil.java:54)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
```
