### ISSUE TITLE
range error

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#553]
```
java.lang.Throwable: Invalid range specified: (7, 6); 
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:252)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:247)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:243)
	at com.intellij.openapi.util.TextRange.<i...
```

**Comment by SingingBush** [comment]
possibly related:

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)

	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)

	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)

	at java.base/java.util.Objects.checkIndex(Objects.java:372)

	at ja..
```

**Comment by SingingBush** [comment]
Closing as there's nothing to go on with this issue.
