### ISSUE TITLE
plugin exception in DExternalAnnotator

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#554]
```
com.intellij.diagnostic.PluginException: annotator: io.github.intellij.dlanguage.highlighting.annotation.external.DExternalAnnotator@59323be7 (class io.github.intellij.dlanguage.highlighting.annotation.external.DExternalAnnotator) [Plugin: net.masterthought.dlanguage]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:405)
	at com.intellij.diagnostic.Plu...
```

IDEA 2019.3.1 on JDK 11

**Comment by SingingBush** [comment]
May 28th:

IDEA 2020.1.2
Java JetBrains 11.0.7
plugin version 1.24.1

```
com.intellij.diagnostic.PluginException: annotator: io.github.intellij.dlanguage.highlighting.annotation.external.DExternalAnnotator@65f0af0b (class io.github.intellij.dlanguage.highlighting.annotation.external.DExternalAnnotator) [Plugin: net.masterthought.dlanguage]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:451)
	at com.intellij.diagnostic.P...
```

**Comment by SingingBush** [comment]
again with version 1.25 on Intellij 2020.2:

```
com.intellij.diagnostic.PluginException: annotator: io.github.intellij.dlanguage.highlighting.annotation.external.DExternalAnnotator@3eeb694f (class io.github.intellij.dlanguage.highlighting.annotation.external.DExternalAnnotator) [Plugin: net.masterthought.dlanguage]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:290)
	at com.intellij.diagnostic.Plu...
```
