### ISSUE TITLE
IllegalStateException: DLangParser.tok must not return null

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#563]
```
java.lang.IllegalStateException: @NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null\n\tat io.github.intellij.dlanguage.parser.DLangParser.$$$reportNull$$$0(DLangParser.java)\n\tat io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8608)\n\tat io.github.intellij.dlanguage.parser.DLangParser.parseAssignExpression(DLangParser.java:1616)\n\tat io.gith...
```

**Comment by SingingBush** [comment]
got another one of these in CLion:

```
ava.lang.IllegalStateException: @NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null
	at io.github.intellij.dlanguage.parser.DLangParser.$$$reportNull$$$0(DLangParser.java)
	at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8608)
	at io.github.intellij.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.java:7826)
	at io.githu...
```

the last action was **EditorBackSpace**

**Comment by SingingBush** [comment]
seeing this again

IDEA 2020.1.2
Java JetBrains 11.0.7
plugin version 1.24.1

```
java.lang.IllegalStateException: @NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null
    at io.github.intellij.dlanguage.parser.DLangParser.$$$reportNull$$$0(DLangParser.java)
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8608)
    at io.github.intellij.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.java:7714)
    at io.githu...
```

**Comment by SingingBush** [comment]
IDEA 2020.2
plugin version 1.25

last action: **Run**

Message: **@NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null**

```
java.lang.IllegalStateException: @NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null
	at io.github.intellij.dlanguage.parser.DLangParser.$$$reportNull$$$0(DLangParser.java)
	at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8608)
	at io.github.intellij.dlanguage.parser.DLangParser.parseIdentifierOrTemplateInstance(DLangParser.java:4326)...
```

**Comment by SingingBush** [comment]
Same again this month (older intellij and plugin: IDEA 2020.1.3 with 1.24.2 plugin):

key | value
-- | --
Additional info: | None
error.message | @NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null
error.stacktrace | java.lang.IllegalStateException: @NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null 	at io.github.intellij.dlanguage.parser.DLangParser.$$$reportNull$$$0(DLangParser.java) 	at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8608) 	at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:2774) 	at io.githu...
Last Action | Debug

**Comment by SingingBush** [comment]
Getting more reports of this now. It's the biggest cause of error reports.

The following was thrown by plugin v1.26 on IDEA 2021.1:

`Failed to build index 'DModuleIndex' for file file:///usr/include/dlang/dmd/etc/c/odbc/sqltypes.d (id = 271358) (file type = D file) [Plugin: net.masterthought.dlanguage]`

```
java.lang.IllegalStateException: @NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null
    at io.github.intellij.dlanguage.parser.DLangParser.$$$reportNull$$$0(DLangParser.java)
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8608)
    at io.github.intellij.dlanguage.parser.DLangParser.parsePrimaryExpression(DLangParser.java:5799)
    at io.github.intellij.dlanguage.parser.DLangParser.unaryExpressionSwitchDefault(DLangParser.java:7675)
    at io.github.intellij.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.java:7800)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9213)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parsePowExpression(DLangParser.java:5670)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9191)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseMulExpression(DLangParser.java:5225)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9181)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAddExpression(DLangParser.java:535)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9125)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseShiftExpression(DLangParser.java:6100)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCmpExpression(DLangParser.java:2291)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9161)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAndExpression(DLangParser.java:788)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9129)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseXorExpression(DLangParser.java:8114)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9215)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseOrExpression(DLangParser.java:5419)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9187)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAndAndExpression(DLangParser.java:766)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9127)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseOrOrExpression(DLangParser.java:5447)
    at io.github.intellij.dlanguage.parser.DLangParser.parseTernaryExpression(DLangParser.java:7223)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAssignExpression(DLangParser.java:1611)
    at io.github.intellij.dlanguage.parser.DLangParser.parseEnumMember(DLangParser.java:3560)
    at io.github.intellij.dlanguage.parser.DLangParser.parseEnumBody(DLangParser.java:3379)
    at io.github.intellij.dlanguage.parser.DLangParser.parseEnumDeclaration(DLangParser.java:3536)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:2870)
    at io.github.intellij.dlanguage.parser.DLangParser.parseModule(DLangParser.java:5179)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:413)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:422)
```

the line of code is here: https://github.com/intellij-dlanguage/intellij-dlanguage/blob/6b6f80271d858c266a5cbad9ee707f95e2f9674f/src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java#L8608

**Comment by SingingBush** [comment]
Intellij IDEA 2021.2:

```
java.lang.IllegalStateException: @NotNull method io/github/intellij/dlanguage/parser/DLangParser.tok must not return null
    at io.github.intellij.dlanguage.parser.DLangParser.$$$reportNull$$$0(DLangParser.java)
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8608)
    at io.github.intellij.dlanguage.parser.DLangParser.isAttribute(DLangParser.java:8343)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:2731)
    at io.github.intellij.dlanguage.parser.DLangParser.parseStructBody(DLangParser.java:6534)
    at io.github.intellij.dlanguage.parser.DLangParser.parseStructDeclaration(DLangParser.java:6568)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:2980)
    at io.github.intellij.dlanguage.parser.DLangParser.parseModule(DLangParser.java:5179)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:413)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:422)
```
