### ISSUE TITLE
IllegalArgumentException in DLangParser.java

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#574]
IDEA 2020.1.1
Java JetBrains 11.0.6
plugin version 1.24.1

```
java.lang.IllegalArgumentException: string:doubleLiteral
 	at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8616)
 	at io.github.intellij.dlanguage.parser.DLangParser.<init>(DLangParser.java:130)
 	at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:23)
 	at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:422)
 	at com....
```

**Comment by SingingBush** [comment]
again with version 1.24.1:

```
java.lang.IllegalArgumentException: string:identifier
 	at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8616)
 	at io.github.intellij.dlanguage.parser.DLangParser.parseIdentifierChain(DLangParser.java:4244)
 	at io.github.intellij.dlanguage.parser.DLangParser.parseSingleImport(DLangParser.java:6123)
 	at io.github.intellij.dlanguage.parser.DLangParser.parseImportDeclaration(...
```

**Comment by SingingBush** [comment]
For now I've just improved the error message

**Comment by SingingBush** [comment]
error.message | Could not find single match for token: 'identifier'. 0 matches found
-- | --
error.stacktrace | java.lang.IllegalArgumentException: Could not find single match for token: 'identifier'. 0 matches found 	at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:8617) 	at io.github.intellij.dlanguage.parser.DLangParser.parseType2(DLangParser.java:7404) 	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9103) 	at io.github.intellij.dlanguage.parser.DL...
Last Action | WelcomeScreen.OpenProject

**Comment by SingingBush** [comment]
This could be related with the change to using a do while loop in `private Token[] getTokens(@NotNull final PsiBuilder builder)`:

```java
        do {
            @Nullable final IElementType tokenType = builder.getTokenType();

            if(tokenType != null) {
                tokens.add(tokenType);
            }

            builder.advanceLexer();
        } while (!builder.eof());
```

I need to find some D source code that can recreate the problem and then do some testing.
