### ISSUE TITLE
IOException

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#576]
not too much to go on here. Needs replicating

IDE: IntelliJ IDEA Ultimate Edition 2020.1.2
plugin version: 1.24.1
Last Action: GotoNextError

```
java.io.IOException: Broken pipe
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:303)
```

**Comment by SingingBush** [comment]
similar report:

```
java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/sun.nio.cs.StreamEncoder.implFlu...
```

**Comment by SingingBush** [comment]
The only thing to go on here was the **GotoNextError** action. I opened a project and cycled through problems with F2 and back with Shift+F2 as per: [Navigate between errors or warnings](https://www.jetbrains.com/help/idea/navigating-through-the-source-code.html#navigate-errors-warnings).

I didn't encounter any problem and there's no other Sentry reports for *IOException* in the last 30 days.
