### ISSUE TITLE
ArrayIndexOutOfBoundsException in DLangParser

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#578]
version: 1.24.1
Last action: FindInPath

```
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
 	at io.github.intellij.dlanguage.parser.DLangParser.current(DLangParser.java:8595)
 	at io.github.intellij.dlanguage.parser.DLangParser.parseContinueStatement(DLangParser.java:2585)
 	at io.github.intellij.dlanguage.parser.DLangParser.parseStatementNoCaseNoDefault(DLangParser.java:6245)
 	at io.github.intellij.dlanguage.p...
```

**Comment by SingingBush** [comment]
Changing anything in DLangParser seems a bit hideous as it's generated code but I've changed:

```
    @Nullable
    private Token current() {
        return tokens[index];
    }
```

to:

```
    @Nullable
    private Token current() {
        return index >= 0 && index < tokens.length ? tokens[index] : null;
    }
```

**Comment by SingingBush** [comment]
Similar issue in v1.25 on Sep 15th but this time on line 8662:

key | value
-- | --
error.message | Index 8 out of bounds for length 8
error.stacktrace | java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8 	at io.github.intellij.dlanguage.parser.DLangParser.advance(DLangParser.java:8662) 	at io.github.intellij.dlanguage.parser.DLangParser.parseIndexExpression(DLangParser.java:4700) 	at io.github.intellij.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.java:7838) 	at io.github.intellij.dlanguage.parser.D...
Last Action | None

**Comment by SingingBush** [comment]
in v1.26 of the plugin there was an ArrayIndexOutOfBoundsException thrown (from WebStorm) on the final line of DLangParser::advance() which does `return tokens[index - 1];`

```
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
    at io.github.intellij.dlanguage.parser.DLangParser.advance(DLangParser.java:8662)
    at io.github.intellij.dlanguage.parser.DLangParser.parseIndexExpression(DLangParser.java:4700)
    at io.github.intellij.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.java:7838)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9213)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parsePowExpression(DLangParser.java:5670)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9191)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseMulExpression(DLangParser.java:5225)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9181)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAddExpression(DLangParser.java:535)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9125)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseShiftExpression(DLangParser.java:6100)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCmpExpression(DLangParser.java:2291)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9161)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAndExpression(DLangParser.java:788)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9129)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseXorExpression(DLangParser.java:8114)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9215)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseOrExpression(DLangParser.java:5419)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9187)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAndAndExpression(DLangParser.java:766)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9127)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8388)
    at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:8378)
    at io.github.intellij.dlanguage.parser.DLangParser.parseOrOrExpression(DLangParser.java:5447)
    at io.github.intellij.dlanguage.parser.DLangParser.parseTernaryExpression(DLangParser.java:7223)
    at io.github.intellij.dlanguage.parser.DLangParser.parseAssignExpression(DLangParser.java:1611)
    at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9159)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaSeparatedRule(DLangParser.java:8422)
    at io.github.intellij.dlanguage.parser.DLangParser.parseCommaSeparatedRule(DLangParser.java:8404)
    at io.github.intellij.dlanguage.parser.DLangParser.parseExpression(DLangParser.java:3648)
    at io.github.intellij.dlanguage.parser.DLangParser.parseExpressionStatement(DLangParser.java:3663)
    at io.github.intellij.dlanguage.parser.DLangParser.parseExpressionStatement(DLangParser.java:9230)
    at io.github.intellij.dlanguage.parser.DLangParser.parseStatementNoCaseNoDefault(DLangParser.java:6358)
    at io.github.intellij.dlanguage.parser.DLangParser.parseStatement(DLangParser.java:6167)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclarationOrStatement(DLangParser.java:3132)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclarationsAndStatements(DLangParser.java:3094)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclarationsAndStatements(DLangParser.java:2119)
    at io.github.intellij.dlanguage.parser.DLangParser.parseBlockStatement(DLangParser.java:1930)
    at io.github.intellij.dlanguage.parser.DLangParser.parseFunctionBody(DLangParser.java:3946)
    at io.github.intellij.dlanguage.parser.DLangParser.parseFunctionDeclaration(DLangParser.java:4123)
    at io.github.intellij.dlanguage.parser.DLangParser.type(DLangParser.java:3056)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:3005)
    at io.github.intellij.dlanguage.parser.DLangParser.parseModule(DLangParser.java:5179)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:413)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:422)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:81)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:192)
    at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:567)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:191)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:248)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:42)
    at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.pushChildren(DefaultStubBuilder.java:95)
    at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:65)
    at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:55)
    at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:33)
    at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:22)
```
