### ISSUE TITLE
PluginException in CLion on welcome screen

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#579]
CLion 2020.1.2
plugin 1.24.1

Last Action: **WelcomeScreen.OpenProject**

```
com.intellij.diagnostic.PluginException: While loading class io.github.intellij.dlanguage.module.DlangModuleBuilder$1: com/intellij/ide/util/projectWizard/ProjectJdkForModuleStep [Plugin: net.masterthought.dlanguage]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoade...
```

**Comment by SingingBush** [comment]
CLion 2020.2
plugin 1.25

Last Action: **WelcomeScreen.OpenProject**

_While loading class io.github.intellij.dlanguage.module.DlangModuleBuilder$1: com/intellij/ide/util/projectWizard/ProjectJdkForModuleStep [Plugin: net.masterthought.dlanguage]_

```
com.intellij.diagnostic.PluginException: While loading class io.github.intellij.dlanguage.module.DlangModuleBuilder$1: com/intellij/ide/util/projectWizard/ProjectJdkForModuleStep [Plugin: net.masterthought.dlanguage]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:261)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoa...
```

also worth noting that this issue is a duplicate of #541

**Comment by SingingBush** [comment]
closing as this is duplicate of #541
