### ISSUE TITLE
PluginException in CLion: Inspection #PossiblyUndefinedSymbol has no description

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#589]
CLion 2020.1.1
Plugin 1.24.2

Message: _Inspection #PossiblyUndefinedSymbol has no description [Plugin: net.masterthought.dlanguage]_

Last Action: **Tree-selectParent**

```
com.intellij.diagnostic.PluginException: Inspection #PossiblyUndefinedSymbol has no description [Plugin: net.masterthought.dlanguage]
	at com.intellij.codeInspection.ui.InspectionNodeInfo.<init>(InspectionNodeInfo.java:74)
	at com.intellij.codeInspection.ui.InspectionResultsView.createBaseRightComponentFor(InspectionResultsView.java:468)
	at com.intellij.codeInspection.ui.InspectionResultsView....
```

**Comment by SingingBush** [comment]
This was caused by a missing file in the `/resources/inspectionDescriptions` directory. There should be an html file for each _localInspection_
