### ISSUE TITLE
DCD: Read access is allowed from event dispatch thread or inside read-action only

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#591]
- IDE: Intellij 2020.2
 - Plugin Version 1.25

There were similar issues (#116, #119, #132) for Write Access. Now a similar problem for read actions. Worth referring to https://github.com/intellij-dlanguage/intellij-dlanguage/issues/417#issuecomment-396403609 to get an idea of what needs to be done.

Additional info: | None
-- | --
error.message | Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
error.stacktrace | java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction()) 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161) 	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1013) 	at com.intellij.psi.impl.source.tree.TreeElement.asse...
Last Action | Run

**Comment by SingingBush** [comment]
got this again on "EditorPaste" but with stack trace that pinpoints DCD:

```
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1009)
    at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:411)
    at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:224)
    at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getText(LazyParseableElement.java:100)
    at com.intellij.psi.AbstractFileViewProvider$PsiFileContent.getText(AbstractFileViewProvider.java:509)
    at com.intellij.psi.AbstractFileViewProvider.getContents(AbstractFileViewProvider.java:159)
    at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:284)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:69)
    at io.github.intellij.dlanguage.codeinsight.DCompletionProvider.lambda$addCompletions$1(DCompletionProvider.java:46)
```

**Comment by SingingBush** [comment]
Numerous similar reports with exception thrown in **DCDCompletionClient**: _autoComplete_ at line 69

Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())

## Additional data

key: | Value
-- | --
error.message | Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
error.stacktrace | java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction()) 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:164) 	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1009) 	at com.intellij.psi.impl.source.tree.TreeElement.asse...
Last Action | *EditorBackSpace*


key: | Value
-- | --
error.message | Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
error.stacktrace | java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction()) 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:164) 	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1009) 	at com.intellij.psi.impl.source.tree.TreeElement.asse...
Last Action | *EditorPaste*


key: | Value
-- | --
error.message | Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
error.stacktrace | java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction()) 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161) 	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1013) 	at com.intellij.psi.impl.source.tree.TreeElement.asse...
Last Action | *ShowSettings*

**Comment by SingingBush** [comment]
this is the most common error being reported. Need to treat _DCDCompletionClient_ as a priority

```
io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionClient in autoComplete at line 69
io.github.intellij.dlanguage.codeinsight.DCompletionProvider in lambda$addCompletions$1 at line 46
```

**Comment by SingingBush** [comment]
reported from Intellij 2021.2 with v1.26.1:

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:969)
    at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:424)
    at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:224)
    at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getText(LazyParseableElement.java:83)
    at com.intellij.psi.AbstractFileViewProvider$PsiFileContent.getText(AbstractFileViewProvider.java:514)
    at com.intellij.psi.AbstractFileViewProvider.getContents(AbstractFileViewProvider.java:158)
    at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:305)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:62)
    at io.github.intellij.dlanguage.codeinsight.DCompletionProvider.lambda$addCompletions$1(DCompletionProvider.java:50)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
    at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by GYUMO** [comment]
Does the problem with "Intellij 2021.2 with v1.26.1 " has solved?

**Comment by SingingBush** [comment]
no, this issue still needs to be fixed

**Comment by SingingBush** [comment]
This is fixed for DCD
