### ISSUE TITLE
add locale for en_US

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#592]
sentry report for MissingResourceException

```
java.util.MissingResourceException: Can't find bundle for base name i18n, locale en_US
 	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
 	at java.base/java.util.ResourceBundle.getBundleImpl(Reso...
```

**Comment by SingingBush** [comment]
There is a `src/main/resources/i18n_en_US.properties` so this should not be a problem. Perhaps the file should be `i18n-en_US.properties`?

**Comment by SingingBush** [comment]
I booted the app with `-Duser.language=fr -Duser.country=FR` and it loaded up french text. The US english works the same way. No idea how this exception ended happening. closing
