### ISSUE TITLE
NoSourcesException when creating a new project

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#617]
- OS: Linux
 - IDE: Intellij 2020.3.3
 - Plugin Version 1.26

```
io.github.intellij.dlanguage.run.exception.NoSourcesException: No D sources found in /home/USERNAME/untitled/source
    at io.github.intellij.dlanguage.run.DlangDmdConfigToArgsConverter.getAllDLangSources(DlangDmdConfigToArgsConverter.java:236)
    at io.github.intellij.dlanguage.run.DlangDmdConfigToArgsConverter.getDmdParameters(DlangDmdConfigToArgsConverter.java:30)
    at io.github.intellij.dlanguage.run.DlangRunDmdConfigurationEditor.fillArguments(DlangRunDmdConfigurationEditor.java:324)
    at io.github.intellij.dlanguage.run.DlangRunDmdConfigurationEditor.resetEditorFrom(DlangRunDmdConfigurationEditor.java:104)
    at io.github.intellij.dlanguage.run.DlangRunDmdConfigurationEditor.resetEditorFrom(DlangRunDmdConfigurationEditor.java:34)
    at com.intellij.openapi.options.SettingsEditor.lambda$resetFrom$0(SettingsEditor.java:76)
    at com.intellij.openapi.options.SettingsEditor.bulkUpdate(SettingsEditor.java:84)
    at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:74)
```

No sources existing should be handled gracefully in most cases but especially when creating a project. The last action on this bug report was *WelcomeScreen.CreateNewProject*

**Comment by SingingBush** [comment]
Looks like this doesn't need resolving as such except for the fact that a lack of source is being logged at error level and therefore generating a bug report via error reporting.

I tested by creating a new D project (non-dub) and then adding the run config for compiling with dmd and finally running the run configuration.

![image](https://user-images.githubusercontent.com/870567/150676213-c94872fc-d8a4-4560-bfff-1a61a0bf48cf.png)

```
There was a problem filling the textArgsPane in DMD config page

io.github.intellij.dlanguage.run.exception.NoSourcesException: No D sources found in /home/samael/IdeaProjects/test_617/source
	at io.github.intellij.dlanguage.run.DlangDmdConfigToArgsConverter.getAllDLangSources(DlangDmdConfigToArgsConverter.java:242)
	at io.github.intellij.dlanguage.run.DlangDmdConfigToArgsConverter.getDmdParameters(DlangDmdConfigToArgsConverter.java:30)
	at io.github.intellij.dlanguage.run.DlangRunDmdConfigurationEditor.fillArguments(DlangRunDmdConfigurationEditor.java:324)
	at io.github.intellij.dlanguage.run.DlangRunDmdConfigurationEditor.resetEditorFrom(DlangRunDmdConfigurationEditor.java:104)
	at io.github.intellij.dlanguage.run.DlangRunDmdConfigurationEditor.resetEditorFrom(DlangRunDmdConfigurationEditor.java:34)
```

A popup was already displayed to notify of the problem so simply changing to log a warning will be fine.

**Comment by SingingBush** [comment]
I also tested similar situation for dub based projects but it doesn't affect them. This is now resolved
