### ISSUE TITLE
PluginException com.intellij.ide.plugins.PluginManagerCore in createPluginException

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#620]
Got a fair few reports of _PluginException_ in various IDE's. Not sure on what's happening when the problem occurs as users generally don't provide any explanation. I think this will happen in IDEA as well but the reports I looked at where for:

 - CLion 2021.1.1 (CL-211.7142.21) with Java 11.0.10 (Jetbrains)
 - PyCharm 2021.1.1 (PY-211.7142.13) with Java 11.0.10 (Jetbrains)

 - `com.intellij.diagnostic.PluginException: Failed to build stub tree for uuid.d [Plugin: net.masterthought.dlanguage]`
 - `com.intellij.diagnostic.PluginException: Failed to build stub tree for medium.d [Plugin: net.masterthought.dlanguage]`

```
com.intellij.openapi.progress.ProcessCanceledException: null
    at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:145)
    at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:136)
    at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceledRaw(ProgressWrapper.java:82)
    at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceled(ProgressWrapper.java:89)
    at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:133)
    at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:230)
    at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:39)
    at com.intellij.lang.impl.PsiBuilderImpl.advanceLexer(PsiBuilderImpl.java:751)
    at com.intellij.lang.impl.PsiBuilderAdapter.advanceLexer(PsiBuilderAdapter.java:39)
    at io.github.intellij.dlanguage.parser.DLangParser.advance(DLangParser.java:8646)
    at io.github.intellij.dlanguage.parser.DLangParser.parseArrayInitializer(DLangParser.java:872)
    at io.github.intellij.dlanguage.parser.DLangParser.parseNonVoidInitializer(DLangParser.java:5358)
    at io.github.intellij.dlanguage.parser.DLangParser.parseStructMemberInitializer(DLangParser.java:6623)
    at io.github.intellij.dlanguage.parser.DLangParser.parseStructMemberInitializers(DLangParser.java:6642)
    at io.github.intellij.dlanguage.parser.DLangParser.parseStructInitializer(DLangParser.java:6596)
    at io.github.intellij.dlanguage.parser.DLangParser.parseNonVoidInitializer(DLangParser.java:5338)
    at io.github.intellij.dlanguage.parser.DLangParser.parseInitializer(DLangParser.java:4774)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclarator(DLangParser.java:3189)
    at io.github.intellij.dlanguage.parser.DLangParser.parseVariableDeclaration(DLangParser.java:7959)
    at io.github.intellij.dlanguage.parser.DLangParser.type(DLangParser.java:3060)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:3005)
    at io.github.intellij.dlanguage.parser.DLangParser.parseConditionalDeclaration(DLangParser.java:2419)
    at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:3011)
    at io.github.intellij.dlanguage.parser.DLangParser.parseModule(DLangParser.java:5179)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:413)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:422)
```

This has been the most common error recently so could really do with getting sorted asap.

**Comment by etienne02** [comment]
We should not catch ProcessCancelledException (of at least rethrow them). Now the parser was rewrote, the issue does not exists anymore.
