### ISSUE TITLE
IllegalArgumentException in DDocumentationProvider::generateDoc

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#627]
- Plugin Version : latest develop branch

```
java.lang.IllegalArgumentException: Asked for attributes of something that isn't a DNamedElement, or the child of a DNamedElement
	at io.github.intellij.dlanguage.resolve.processors.parameters.DAttributesFinder.<init>(DAttributesFinder.kt:35)
	at io.github.intellij.dlanguage.features.DDocumentationProvider.generateDoc(DDocumentationProvider.java:49)
	at com.intellij.lang.documentation.DocumentationProvider.generateHoverDoc(DocumentationProvider.java:112)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateHoverDoc(CompositeDocumentationProvider.java:151)
	at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.lambda$getDocumentation$2(DocumentationManager.java:1572)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
```

**Comment by SingingBush** [comment]
this bug is now fixed. It would be good to improve the _DDocumentationProvider_ but that should be done as another issue.
