### ISSUE TITLE
Rename D Source Files With "Search for References" Checked

### ISSUE THREAD

**Issue by benoit-dubreuil** [intellij-dlanguage/intellij-dlanguage#632]
**Desktop (please provide environment info):**
 - OS: Windows 10
 - IDE: Intellij 2021.2.1 (Ultimate Edition)
 - Plugin Version: 1.26.1

**D compiler and tools (please provide version numbers):**
 - dmd: 2.097.2
 - dub: 1.26.1
 - dcd: 0.13.4
 - dscanner: 0.11.1-1

**Describe the problem**
When I try to rename a D code file through the project view and the "search for references" checkbox is checked, nothing happens except an error in the event log.

**Please provide full details to reproduce the problem**
- Open a D project in IntelliJ that contains at least 1 `.d` file.
- In the project view, trigger the rename action on a `.d` file .
- Check the "search for references" checkbox in window that just popped up.
- Trigger the rename by clicking on the "refactor" button.
- Notice that the file was not renamed and that IntelliJ's event log flashes red.

**Screenshots**
![image](https://user-images.githubusercontent.com/6900372/130657026-80b72778-e999-4db4-9365-ca9cff540fa0.png)

**Additional context**
I have only 1 `.d` file in my project.

**Possibly related issues**
- #103
- #596

**Stack trace**
<details>
  <summary>Click to expand!</summary>
  
```
java.lang.IllegalStateException: Something went horribly wrong while renaming. Target nane:main.d ProjectProject(name=cg-math, containerState=COMPONENT_CREATED, componentStore=C:\Users\********\Documents\***\Workspace\Personal\***********\cg-math) e:null
	at io.github.intellij.dlanguage.psi.impl.named.DlangIdentifierImpl.setName(DlangIdentifierImpl.java:82)
	at io.github.intellij.dlanguage.psi.references.DReference.handleElementRename(DReference.kt:268)
	at com.intellij.refactoring.rename.RenameUtilBase.rename(RenameUtilBase.java:90)
	at com.intellij.refactoring.rename.RenameUtilBase.doRenameGenericNamedElement(RenameUtilBase.java:46)
	at com.intellij.refactoring.rename.RenameUtil.doRenameGenericNamedElement(RenameUtil.java:270)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.renameElement(RenamePsiElementProcessor.java:55)
	at com.intellij.refactoring.rename.RenameProcessor.doPerformRefactoring(RenameProcessor.java:429)
	at com.intellij.refactoring.rename.RenameProcessor.performRefactoring(RenameProcessor.java:373)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$9(BaseRefactoringProcessor.java:522)
	at com.intellij.refactoring.BaseRefactoringProcessor.callPerformRefactoring(BaseRefactoringProcessor.java:575)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$10(BaseRefactoringProcessor.java:521)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$11(ApplicationImpl.java:900)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$12(ApplicationImpl.java:900)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runEdtProgressWriteAction(ApplicationImpl.java:898)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithNonCancellableProgressInDispatchThread(ApplicationImpl.java:879)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRefactoring(BaseRefactoringProcessor.java:520)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$execute$2(BaseRefactoringProcessor.java:337)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:335)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRun(BaseRefactoringProcessor.java:258)
	at com.intellij.refactoring.rename.RenameProcessor.doRun(RenameProcessor.java:126)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:152)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$run$18(BaseRefactoringProcessor.java:636)
	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:650)
	at com.intellij.refactoring.ui.RefactoringDialog.invokeRefactoring(RefactoringDialog.java:233)
	at com.intellij.refactoring.rename.RenameDialog.performRename(RenameDialog.java:336)
	at com.intellij.refactoring.rename.RenameDialog.doAction(RenameDialog.java:314)
	at com.intellij.refactoring.rename.RenameWithOptionalReferencesDialog.doAction(RenameWithOptionalReferencesDialog.java:44)
	at com.intellij.refactoring.ui.RefactoringDialog.doRefactorAction(RefactoringDialog.java:128)
	at com.intellij.refactoring.ui.RefactoringDialog$RefactorAction.actionPerformed(RefactoringDialog.java:211)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:816)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:699)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1726)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1685)
	at com.intellij.refactoring.ui.RefactoringDialog.show(RefactoringDialog.java:95)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:201)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:167)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:162)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:114)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:81)
	at com.intellij.refactoring.actions.BaseRefactoringAction.performRefactoringAction(BaseRefactoringAction.java:160)
	at com.intellij.refactoring.rename.RenameHandler2Renamer.lambda$performRename$0(RenameHandler2Renamer.java:38)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:152)
	at com.intellij.refactoring.rename.RenameHandler2Renamer.performRename(RenameHandler2Renamer.java:36)
	at com.intellij.refactoring.actions.RenameElementAction.actionPerformed(RenameElementAction.java:80)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:563)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:677)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:574)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:457)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:450)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:800)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

**Comment by SingingBush** [comment]
Thanks for providing details of how to recreate the problem and the screenshot. If you open the event log it'll show a stack trace. Could you please paste it into this issue or submit it from the event log directly.

**Comment by benoit-dubreuil** [comment]
> Thanks for providing details of how to recreate the problem and the screenshot. If you open the event log it'll show a stack trace. Could you please paste it into this issue or submit it from the event log directly.

Done, @SingingBush!

**Comment by SingingBush** [comment]
thanks. So it looks like you were renaming cg-math to main.d and then _DlangIdentifierImpl::setName_ got in a bad state on line 78: `final PsiElement e = DElementFactory.createDLanguageIdentifierFromText(getProject(), newName);` as there is a null check following it that throws the resulting exception:

```java
    @NotNull
    public PsiElement setName(@NotNull final String newName) {
        final PsiElement e = DElementFactory.createDLanguageIdentifierFromText(getProject(), newName);
        if (e == null) {
            throw new IllegalStateException(
                "Something went horribly wrong while renaming. Target nane:" + newName + " Project"
                    + getProject().toString() + " e:" + e);
        }
        replace(e);
        return this;
    }
```

Perhaps if the psi element is null it should just `return this` instead of throwing the error, perhaps logging a warning. Not sure without digging deeper. It needs more time and testing.

Presuming this is your stacktrace:

```
java.lang.IllegalStateException: Something went horribly wrong while renaming. Target nane:main.d ProjectProject(name=cg-math, containerState=COMPONENT_CREATED, componentStore=C:\Users\********\Documents\***\Workspace\Personal\***********\cg-math) e:null
    at io.github.intellij.dlanguage.psi.impl.named.DlangIdentifierImpl.setName(DlangIdentifierImpl.java:82)
    at io.github.intellij.dlanguage.psi.references.DReference.handleElementRename(DReference.kt:268)
    at com.intellij.refactoring.rename.RenameUtilBase.rename(RenameUtilBase.java:90)
    at com.intellij.refactoring.rename.RenameUtilBase.doRenameGenericNamedElement(RenameUtilBase.java:46)
    at com.intellij.refactoring.rename.RenameUtil.doRenameGenericNamedElement(RenameUtil.java:270)
    at com.intellij.refactoring.rename.RenamePsiElementProcessor.renameElement(RenamePsiElementProcessor.java:55)
    at com.intellij.refactoring.rename.RenameProcessor.doPerformRefactoring(RenameProcessor.java:429)
    at com.intellij.refactoring.rename.RenameProcessor.performRefactoring(RenameProcessor.java:373)
    at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$9(BaseRefactoringProcessor.java:522)
    at com.intellij.refactoring.BaseRefactoringProcessor.callPerformRefactoring(BaseRefactoringProcessor.java:575)
    at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$10(BaseRefactoringProcessor.java:521)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$11(ApplicationImpl.java:900)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:197)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runEdtProgressWriteAction$12(ApplicationImpl.java:900)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
    at com.intellij.openapi.application.impl.ApplicationImpl.runEdtProgressWriteAction(ApplicationImpl.java:898)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithNonCancellableProgressInDispatchThread(ApplicationImpl.java:879)
    at com.intellij.refactoring.BaseRefactoringProcessor.doRefactoring(BaseRefactoringProcessor.java:520)
    at com.intellij.refactoring.BaseRefactoringProcessor.lambda$execute$2(BaseRefactoringProcessor.java:337)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
    at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:335)
    at com.intellij.refactoring.BaseRefactoringProcessor.doRun(BaseRefactoringProcessor.java:258)
    at com.intellij.refactoring.rename.RenameProcessor.doRun(RenameProcessor.java:126)
    at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:152)
    at com.intellij.refactoring.BaseRefactoringProcessor.lambda$run$18(BaseRefactoringProcessor.java:636)
    at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:650)
    at com.intellij.refactoring.ui.RefactoringDialog.invokeRefactoring(RefactoringDialog.java:233)
    at com.intellij.refactoring.rename.RenameDialog.performRename(RenameDialog.java:336)
    at com.intellij.refactoring.rename.RenameDialog.doAction(RenameDialog.java:314)
    at com.intellij.refactoring.rename.RenameWithOptionalReferencesDialog.doAction(RenameWithOptionalReferencesDialog.java:44)
    at com.intellij.refactoring.ui.RefactoringDialog.doRefactorAction(RefactoringDialog.java:128)
    at com.intellij.refactoring.ui.RefactoringDialog$RefactorAction.actionPerformed(RefactoringDialog.java:211)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
    at java.awt.Component.processMouseEvent(Component.java:6652)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
    at java.awt.Component.processEvent(Component.java:6417)
    at java.awt.Container.processEvent(Container.java:2263)
    at java.awt.Component.dispatchEventImpl(Component.java:5027)
    at java.awt.Container.dispatchEventImpl(Container.java:2321)
    at java.awt.Component.dispatchEvent(Component.java:4859)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
    at java.awt.Container.dispatchEventImpl(Container.java:2307)
    at java.awt.Window.dispatchEventImpl(Window.java:2784)
    at java.awt.Component.dispatchEvent(Component.java:4859)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
    at java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    at java.awt.EventQueue$5.run(EventQueue.java:751)
    at java.awt.EventQueue$5.run(EventQueue.java:749)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
    at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:816)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
    at java.awt.Dialog.show(Dialog.java:1063)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:699)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)
    at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1726)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1685)
    at com.intellij.refactoring.ui.RefactoringDialog.show(RefactoringDialog.java:95)
    at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:201)
    at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:167)
    at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:162)
    at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:114)
    at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:81)
    at com.intellij.refactoring.actions.BaseRefactoringAction.performRefactoringAction(BaseRefactoringAction.java:160)
    at com.intellij.refactoring.rename.RenameHandler2Renamer.lambda$performRename$0(RenameHandler2Renamer.java:38)
    at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:152)
    at com.intellij.refactoring.rename.RenameHandler2Renamer.performRename(RenameHandler2Renamer.java:36)
    at com.intellij.refactoring.actions.RenameElementAction.actionPerformed(RenameElementAction.java:80)
    at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:563)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:677)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:670)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:574)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:457)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:450)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
    at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:800)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Is this something you'd be willing to dig into and make a pull request for? By checking out the develop branch and running `./gradlew runIde` in the project root you can spin up a sandboxed Intellij IDEA and test code changes

**Comment by benoit-dubreuil** [comment]
> So it looks like you were renaming cg-math to main.d ...

Actually, I was renaming a `main.d` source file to `dummy.d`.


> Is this something you'd be willing to dig into and make a pull request for? By checking out the develop branch and running `./gradlew runIde` in the project root you can spin up a sandboxed Intellij IDEA and test code changes

I could try. However, please understand that I am a junior CS developer, so I might ask some general directions depending on how it goes. Hopefully it is a simple and easy to fix bug.

**Comment by benoit-dubreuil** [comment]
I'm sorry, but I give up.

I encountered many problems related to the development environnement (compilation, dependencies, bugs, etc). Just when I was finally able to launch the sandboxed Intellij IDEA, it was so bugged that I couldn't do any testing / debugging. I couldn't create files or interact with the project tree structure.

Thank you again @SingingBush and I also apologize, but I'll pass.

**Comment by SingingBush** [comment]
ok no problem. At least for now unchecking "Search for references" should work around the issue. There are some other bugs I want to focus on so this issue may go unresolved for a while.

**Comment by SingingBush** [comment]
another related stack trace:

```
java.lang.Throwable: Invalid parent: file://C:/Users/******/Documents/******/Workspace/Personal/******/cg-math/src/cg/math/dummy/test (invalid) of file file://C:/Users/******/Documents/******/Workspace/Personal/******/cg-math/src/cg/math/dummy/test/d.d (invalid), file.valid=false
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
    at com.intellij.psi.impl.source.PsiFileImpl.getContainingDirectory(PsiFileImpl.java:432)
    at com.intellij.psi.impl.source.PsiFileImpl.getParent(PsiFileImpl.java:422)
    at com.intellij.psi.impl.source.PsiFileImpl.getParent(PsiFileImpl.java:50)
    at io.github.intellij.dlanguage.presentation.UtilsKt$psiElementGetVisibility$1.invoke(Utils.kt:145)
    at io.github.intellij.dlanguage.presentation.UtilsKt.psiElementGetVisibility(Utils.kt:149)
    at io.github.intellij.dlanguage.structure.DStructureViewElement.getPresentation(DStructureViewElement.kt:126)
    at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:42)
    at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:78)
    at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:30)
    at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:455)
    at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:436)
    at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:429)
    at com.intellij.ui.tree.StructureTreeModel.getValidRoot(StructureTreeModel.java:367)
    at com.intellij.ui.tree.StructureTreeModel.getRoot(StructureTreeModel.java:282)
    at com.intellij.ui.tree.StructureTreeModel.getRoot(StructureTreeModel.java:34)
    at com.intellij.ui.tree.AsyncTreeModel$CmdGetRoot.getNode(AsyncTreeModel.java:469)
    at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
    at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
```

**Comment by etienne02** [comment]
For this one I have a proper fix and a hack fix:

1. The hack fix is to always remove the ".d" to the identifier if there is one
2. The proper fix is to do like [python](https://github.com/JetBrains/intellij-community/blob/305f32905748f324273245ca74d995c9856e0fbd/python/python-psi-impl/src/com/jetbrains/python/psi/impl/references/PyReferenceImpl.java#L450).

My problem is when I do 2., it sometimes fails because it rename the module before the references to the module. I’m not sure but I think there is a missing back link from the module to his references to force intellij to rename in good order (references then module then file)
