### ISSUE TITLE
IndexNotReadyException in DPublicImportIndex

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#650]
plugin 1.27 on Intellij 2021.3

```
om.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
    at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:852)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:804)
    at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:514)
    at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:318)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
    at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.getAllPubliclyImported(DImportIndex.kt:56)
    at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.recursivelyGetAllPublicImports(DImportIndex.kt:45)
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:64)
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.execute(DNameScopeProcessor.kt:41)
    at io.github.intellij.dlanguage.resolve.ScopeProcessorImplUtil.processDeclaration(ScopeProcessorImplUtil.kt:77)
    at io.github.intellij.dlanguage.psi.DlangFile.processDeclarations(DlangFile.java:105)
    at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1203)
    at io.github.intellij.dlanguage.resolve.processors.basic.BasicResolve.findDefinitionNode(BasicResolve.kt:42)
    at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNodeImpl(DResolveUtil.kt:55)
    at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNode(DResolveUtil.kt:37)
    at io.github.intellij.dlanguage.psi.references.DReference.multiResolve(DReference.kt:53)
    at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.resolves(PsiMultiReference.java:51)
    at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.lambda$static$0(PsiMultiReference.java:36)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
    at java.util.TimSort.sort(TimSort.java:220)
    at java.util.Arrays.sort(Arrays.java:1441)
```

**Comment by SingingBush** [comment]
this is still a problem in 1.28.1 (reported from IDEA 2022.1.3)

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
    at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:844)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:792)
    at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:352)
    at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:159)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:99)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:87)
    at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.getAllPubliclyImported(DImportIndex.kt:56)
    at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.recursivelyGetAllPublicImports(DImportIndex.kt:45)
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:64)
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.execute(DNameScopeProcessor.kt:41)
    at io.github.intellij.dlanguage.resolve.ScopeProcessorImplUtil.processDeclaration(ScopeProcessorImplUtil.kt:77)
    at io.github.intellij.dlanguage.psi.DlangFile.processDeclarations(DlangFile.java:120)
    at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1255)
```

**Comment by SingingBush** [comment]
IDEA: 2022.2.3
plugin: 1.28.3

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
    at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:844)
    at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:792)
    at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:350)
    at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:157)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:99)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:87)
    at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.getAllPubliclyImported(DImportIndex.kt:54)
    at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.recursivelyGetAllPublicImports(DImportIndex.kt:42)
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:66)
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.execute(DNameScopeProcessor.kt:41)
    at io.github.intellij.dlanguage.resolve.ScopeProcessorImplUtil.processDeclaration(ScopeProcessorImplUtil.kt:77)
    at io.github.intellij.dlanguage.psi.DlangFile.processDeclarations(DlangFile.java:120)
```
