### ISSUE TITLE
Exception in DUtil getParentClassOrStructOrTemplateOrInterfaceOrUnion

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#651]
reported by version 1.26.2 on Intellij 2021.1.3 on Windows 10 (december 13th)

`DUtil::getParentClassOrStructOrTemplateOrInterfaceOrUnion` on line 69

```
java.lang.Exception: null
    at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:168)
    at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:134)
    at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:101)
    at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:62)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:237)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:235)
    at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:60)
    at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:202)
    at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:150)
    at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:210)
    at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:730)
    at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
    at com.intellij.extapi.psi.StubBasedPsiElementBase.getParent(StubBasedPsiElementBase.java:319)
    at com.intellij.psi.util.PsiTreeUtil.getParentOfType(PsiTreeUtil.java:859)
    at io.github.intellij.dlanguage.utils.DUtil.getParentClassOrStructOrTemplateOrInterfaceOrUnion(DUtil.java:69)
    at io.github.intellij.dlanguage.psi.impl.named.DLanguageConstructorImpl.getNameIdentifier(DLanguageConstructorImpl.java:99)
    at io.github.intellij.dlanguage.psi.impl.named.DLanguageConstructorImpl.getNameIdentifier(DLanguageConstructorImpl.java:28)
    at io.github.intellij.dlanguage.psi.references.DReference.multiResolve(DReference.kt:53)
    at io.github.intellij.dlanguage.psi.references.DReference.resolve(DReference.kt:66)
```

**Comment by etienne02** [comment]
Closed by #940
