### ISSUE TITLE
DPublicImportIndex.recursivelyGetAllPublicImports() takes too long : Slow operations are prohibited on EDT

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#657]
- IDE: Intellij IDEA 2021.2
 - Plugin Version 1.27.2

editing pretty basic code to test syntax highlighting, found following stack trace:

```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:110)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:754)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:501)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:305)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:100)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:88)
	at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.getAllPubliclyImported(DImportIndex.kt:56)
	at io.github.intellij.dlanguage.stubs.index.DPublicImportIndex$Companion.recursivelyGetAllPublicImports(DImportIndex.kt:45)
	at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:64)
	at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.execute(DNameScopeProcessor.kt:41)
	at io.github.intellij.dlanguage.resolve.ScopeProcessorImplUtil.processDeclaration(ScopeProcessorImplUtil.kt:77)
	at io.github.intellij.dlanguage.psi.DlangFile.processDeclarations(DlangFile.java:105)
	at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1218)
	at io.github.intellij.dlanguage.resolve.processors.basic.BasicResolve.findDefinitionNode(BasicResolve.kt:42)
	at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNodeImpl(DResolveUtil.kt:55)
	at io.github.intellij.dlanguage.resolve.DResolveUtil.findDefinitionNode(DResolveUtil.kt:37)
	at io.github.intellij.dlanguage.codeinsight.ParameterInfo.showParameterInfo(ParameterInfo.kt:45)
	at io.github.intellij.dlanguage.codeinsight.ParameterInfo.showParameterInfo(ParameterInfo.kt:24)
	at com.intellij.codeInsight.hint.ShowParameterInfoHandler.lambda$invoke$0(ShowParameterInfoHandler.java:99)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:163)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:588)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:162)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.hint.ShowParameterInfoHandler.lambda$invoke$1(ShowParameterInfoHandler.java:97)
	at com.intellij.codeInsight.hint.ShowParameterInfoHandler.lambda$invoke$5(ShowParameterInfoHandler.java:112)
	at com.intellij.codeInsight.hint.ParameterInfoTaskRunnerUtil.lambda$runTask$0(ParameterInfoTaskRunnerUtil.java:67)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:577)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Need to start digging around here https://github.com/intellij-dlanguage/intellij-dlanguage/blob/c9ec066b318c3e96e02a877386bebafec9154b5a/src/main/kotlin/io/github/intellij/dlanguage/attributes/DNameScopeProcessor.kt#L64

**Comment by SingingBush** [comment]
this should be looked at at the same time as #650

**Comment by SingingBush** [comment]
may need to use something like

```
DumbService.getInstance(project).runWhenSmart(() -> {
  // your code
});
```
