### ISSUE TITLE
error reported from ProcessDLibs::dubFetch

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#659]
reported from Intellij 2021.3 with plugin v1.27.1

```
java.lang.Throwable: Error when running '/usr/bin/dub fetch labs:dm@~dlang' : (1): Error: Got JSON of type null_, expected object.

    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
    at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.dubFetch(ProcessDLibs.kt:273)
    at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.getSourcesVirtualFile(ProcessDLibs.kt:224)
    at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.createLibraryDependency(ProcessDLibs.kt:178)
    at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.processDLibsImpl(ProcessDLibs.kt:136)
    at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.access$processDLibsImpl(ProcessDLibs.kt:72)
    at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion$processDLibs$2$task$1.run(ProcessDLibs.kt:102)
    at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by SingingBush** [comment]
Turned out the error report was an error within dub that was being logged at error level.

```
$ dub fetch labs:dm@~dlang
(1): Error: Got JSON of type null_, expected object.
```

I've changed the log level to warning as it's right that that command would not work. Ideally it would be good to know how the plugin ended up trying to run dub fetch for a package called _labs:dm_ with the version number of _~dlang_ but for that I'd need to get more info from the user that submitted the error report.
