### ISSUE TITLE
NullPointerException in DlangRunAppConfiguration

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#663]
```
ava.lang.NullPointerException: null
    at io.github.intellij.dlanguage.run.DlangRunAppConfiguration.getExecutablePath(DlangRunAppConfiguration.java:54)
    at io.github.intellij.dlanguage.run.DlangRunAppConfigurationEditor.resetEditorFrom(DlangRunAppConfigurationEditor.java:44)
    at io.github.intellij.dlanguage.run.DlangRunAppConfigurationEditor.resetEditorFrom(DlangRunAppConfigurationEditor.java:21)
    at com.intellij.openapi.options.SettingsEditor.lambda$resetFrom$0(SettingsEditor.java:77)
    at com.intellij.openapi.options.SettingsEditor.bulkUpdate(SettingsEditor.java:85)
    at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:75)
    at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:311)
    at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:294)
    at com.intellij.openapi.options.CompositeSettingsEditor.resetEditorFrom(CompositeSettingsEditor.java:44)
    at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:129)
    at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:31)
    at com.intellij.openapi.options.SettingsEditor.lambda$resetFrom$0(SettingsEditor.java:77)
    at com.intellij.openapi.options.SettingsEditor.bulkUpdate(SettingsEditor.java:85)
    at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:75)
    at com.intellij.openapi.options.SettingsEditorConfigurable.reset(SettingsEditorConfigurable.java:39)
    at com.intellij.execution.impl.SingleConfigurationConfigurable.reset(SingleConfigurationConfigurable.java:180)
    at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:117)
    at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:866)
    at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:901)
    at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:943)
    at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:914)
    at com.intellij.execution.impl.NewRunConfigurationPopup$5.onChosen(NewRunConfigurationPopup.java:249)
    at com.intellij.ui.popup.tree.TreePopupImpl.handleSelect(TreePopupImpl.java:360)
    at com.intellij.ui.popup.tree.TreePopupImpl$MyMouseListener.mousePressed(TreePopupImpl.java:310)
```

this scenario should be handled more gracefully

**Comment by SingingBush** [comment]
closing as this really should no be a problem in either develop branch or in last release as null check is already in use
