### ISSUE TITLE
ArrayIndexOutOfBoundsException in DubProcessListener

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#719]
Plugin Version 1.28.1

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 533 out of bounds for byte[274]
    at java.lang.System.arraycopy(System.java)
    at java.lang.String.getBytes(String.java:3192)
    at java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1667)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
    at java.lang.StringBuilder.append(StringBuilder.java:178)
    at io.github.intellij.dlanguage.tools.dub.DubProcessListener.onTextAvailable(DubProcessListener.kt:24)
    at jdk.internal.reflect.GeneratedMethodAccessor39.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:248)
    at com.sun.proxy.$Proxy47.onTextAvailable
    at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:22
```

**Comment by SingingBush** [comment]
Not sure how this happened but it's doesn't seem to be a problem with the project's code:

```kotlin
    override fun onTextAvailable(event: ProcessEvent, outputType: Key<*>) {
        when (outputType) {
            ProcessOutputTypes.STDOUT -> stdout.append(event.text)
            ProcessOutputTypes.STDERR -> errors.add(event.text.removeSuffix("\n"))
            //ProcessOutputTypes.SYSTEM
        }
        output.append(event.text) <-- The error occurred here
    }
```

both event and event.text are non-null so appending to the string builder should be fine

**Comment by SingingBush** [comment]
this is probably happening because _StringBuilder_ is not thread-safe, switching to _StringBuffer_ should solve the problem

**Comment by SingingBush** [comment]
I've switched over to using a StringBuffer in all the _ProcessAdapter_ classes
