### ISSUE TITLE
NullpointerException when opening dmd project

### ISSUE THREAD

**Issue by etienne02** [intellij-dlanguage/intellij-dlanguage#722]
**Desktop (please provide environment info):**
 - OS: Linux archlinux latest
 - IDE: Intellij 2022.2
 - Plugin Version 1.28.1

**D compiler and tools (please provide version numbers):**
 - dmd: 2.100.0

**Describe the problem**
```
java.lang.NullPointerException
	at io.github.intellij.dlanguage.parser.DLangParser.parseStatementNoCaseNoDefault(DLangParser.java:6896)
	at io.github.intellij.dlanguage.parser.DLangParser.parseScopeGuardStatement(DLangParser.java:6655)
	at io.github.intellij.dlanguage.parser.DLangParser.parseStatementNoCaseNoDefault(DLangParser.java:6968)
	at io.github.intellij.dlanguage.parser.DLangParser.parseStatement(DLangParser.java:6855)
	at io.github.intellij.dlanguage.parser.DLangParser.parseDeclarationOrStatement(DLangParser.java:3250)
	at io.github.intellij.dlanguage.parser.DLangParser.parseDeclarationsAndStatements(DLangParser.java:3208)
	at io.github.intellij.dlanguage.parser.DLangParser.parseDeclarationsAndStatements(DLangParser.java:2193)
	at io.github.intellij.dlanguage.parser.DLangParser.parseBlockStatement(DLangParser.java:2013)
	at io.github.intellij.dlanguage.parser.DLangParser.parseSpecifiedFunctionBody(DLangParser.java:6811)
	at io.github.intellij.dlanguage.parser.DLangParser.parseFunctionLiteralExpression(DLangParser.java:4437)
	at io.github.intellij.dlanguage.parser.DLangParser.parsePrimaryExpression(DLangParser.java:6413)
	at io.github.intellij.dlanguage.parser.DLangParser.unaryExpressionSwitchDefault(DLangParser.java:8385)
	at io.github.intellij.dlanguage.parser.DLangParser.parseUnaryExpression(DLangParser.java:8514)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9956)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parsePowExpression(DLangParser.java:6249)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9934)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parseMulExpression(DLangParser.java:5666)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9924)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parseAddExpression(DLangParser.java:548)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9868)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parseShiftExpression(DLangParser.java:6723)
	at io.github.intellij.dlanguage.parser.DLangParser.parseCmpExpression(DLangParser.java:2368)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9904)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parseAndExpression(DLangParser.java:825)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9872)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parseXorExpression(DLangParser.java:8833)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9958)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parseOrExpression(DLangParser.java:5883)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9930)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parseAndAndExpression(DLangParser.java:803)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9870)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9109)
	at io.github.intellij.dlanguage.parser.DLangParser.parseLeftAssocBinaryExpression(DLangParser.java:9099)
	at io.github.intellij.dlanguage.parser.DLangParser.parseOrOrExpression(DLangParser.java:5911)
	at io.github.intellij.dlanguage.parser.DLangParser.parseTernaryExpression(DLangParser.java:7913)
	at io.github.intellij.dlanguage.parser.DLangParser.parseAssignExpression(DLangParser.java:1695)
	at io.github.intellij.dlanguage.parser.DLangParser.parseTypeIdentifierPart(DLangParser.java:4538)
	at io.github.intellij.dlanguage.parser.DLangParser.parseType2(DLangParser.java:8100)
	at io.github.intellij.dlanguage.parser.DLangParser.parseName(DLangParser.java:9844)
	at io.github.intellij.dlanguage.parser.DLangParser.parseNodeQ(DLangParser.java:9470)
	at io.github.intellij.dlanguage.parser.DLangParser.parseType(DLangParser.java:8044)
	at io.github.intellij.dlanguage.parser.DLangParser.type(DLangParser.java:3151)
	at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:3106)
	at io.github.intellij.dlanguage.parser.DLangParser.parseDeclaration(DLangParser.java:2802)
	at io.github.intellij.dlanguage.parser.DLangParser.parseModule(DLangParser.java:5614)
	at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:439)
	at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:448)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:58)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:175)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:174)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:226)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:24)
	at io.github.intellij.dlanguage.features.formatter.DFormattingModelBuilder$DFormattingBlock.buildSubBlocks(DFormattingModelBuilder.kt:107)
	at io.github.intellij.dlanguage.features.formatter.DFormattingModelBuilder$DFormattingBlock.getSubBlocks(DFormattingModelBuilder.kt:99)
	at com.intellij.psi.formatter.common.NewLineBlocksIterator.pushAll(NewLineBlocksIterator.java:135)
	at com.intellij.psi.formatter.common.NewLineBlocksIterator.next(NewLineBlocksIterator.java:105)
	at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.getBlocksStartingNewLine(FormatterBasedLineIndentInfoBuilder.java:130)
	at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.build(FormatterBasedLineIndentInfoBuilder.java:54)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.calcLineIndentInfo(IndentOptionsDetectorImpl.java:88)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.getIndentOptionsAdjuster(IndentOptionsDetectorImpl.java:52)
	at com.intellij.psi.codeStyle.DetectAndAdjustIndentOptionsTask.calcIndentAdjuster(DetectAndAdjustIndentOptionsTask.java:67)
	at com.intellij.psi.codeStyle.DetectAndAdjustIndentOptionsTask.lambda$scheduleInBackgroundForCommittedDocument$1(DetectAndAdjustIndentOptionsTask.java:104)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.withTimeout(ProgressIndicatorUtils.java:317)
	at com.intellij.psi.codeStyle.DetectAndAdjustIndentOptionsTask.lambda$scheduleInBackgroundForCommittedDocument$2(DetectAndAdjustIndentOptionsTask.java:103)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Please provide full details to reproduce the problem**
It occurs when opening the dmd project

**Screenshots**

**Additional context**

**Comment by SingingBush** [comment]
possibly related to #578
