### ISSUE TITLE
ProcessDLibs can through NullPointerException when there's no module to select

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#730]
- IDE: Intellij 2021.3 (affects all products)
 - Plugin Version 1.28.1

While doing some local dev I ran IDEA and opened a project. The project didn't load properly due to another issue but I was able to work around this and configure dmd and dub. I then selected the process D Libs action but the popup for module selection was blank (due to the failed project import). I was not able to select a module so the ProcessDLibs class through a NullPointerException.

```
java.lang.NullPointerException: null cannot be cast to non-null type com.intellij.openapi.module.Module
	at io.github.intellij.dlanguage.actions.ProcessDLibs$Companion.showModuleChoicePopup$lambda-2(ProcessDLibs.kt:179)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1508)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:186)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:175)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1505)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:136)
```

**Comment by SingingBush** [comment]
for clarity the popup is generated when selecting this action from the menu:
![image](https://user-images.githubusercontent.com/870567/175942281-2aab295d-4a64-4939-9eb6-919354949d2a.png)
