### ISSUE TITLE
AssertionError: Wrong line separators caused by DFormatAction

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#765]
plugin version 1.28.2

```
java.lang.AssertionError: Wrong line separators: '...  } else {\r\n        ...' at offset 43719
    at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2450)
    at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:715)
    at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:609)
    at com.intellij.openapi.editor.impl.DocumentImpl.lambda$setText$2(DocumentImpl.java:1086)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
    at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:1091)
    at io.github.intellij.dlanguage.actions.DFormatAction$1.lambda$processTerminated$0(DFormatAction.java:129)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
```

**Comment by rikkimax** [comment]
I've run into this issue again, I worked around it by setting both IDE and dfmt to use \n for line ending.

I've gone through dfmt, I couldn't find anything obviously wrong with how its handling new line separators.

It doesn't look like we can workaround this in the plugin by changing what is called wrt. Document. It would need to be processed to unify line endings.

I've had a few issues surrounding line endings, I'm wondering if this is actually caused by standard IO rather than dfmt.
