### ISSUE TITLE
DCDCompletionClient running autoComplete in wrong thread

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#790]
A few reports of `java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())`

x3 in last week

IDE: Intellij 2022.2.3
plugin: 1.28.4
Windows

_DCDCompletionClient::autoComplete_

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1056)
    at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:424)
    at com.intellij.psi.impl.source.tree.CompositeElement.getTextLength(CompositeElement.java:463)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getTextLength(LazyParseableElement.java:106)
    at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:226)
    at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getText(LazyParseableElement.java:83)
    at com.intellij.psi.AbstractFileViewProvider$PsiFileContent.getText(AbstractFileViewProvider.java:514)
    at com.intellij.psi.AbstractFileViewProvider.getContents(AbstractFileViewProvider.java:158)
    at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:308)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:77)
    at io.github.intellij.dlanguage.codeinsight.DCompletionProvider.lambda$addCompletions$2(DCompletionProvider.java:51)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
    at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by SingingBush** [comment]
Another report of this error on Feb 10th

plugin version 1.29.3
Intellij IDEA CE 2022.3.2 (Windows 10)

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1013)
    at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:424)
    at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:224)
    at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getText(LazyParseableElement.java:83)
    at com.intellij.psi.AbstractFileViewProvider$PsiFileContent.getText(AbstractFileViewProvider.java:514)
    at com.intellij.psi.AbstractFileViewProvider.getContents(AbstractFileViewProvider.java:158)
    at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:308)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:77)
    at io.github.intellij.dlanguage.codeinsight.DCompletionProvider.lambda$addCompletions$2(DCompletionProvider.java:51)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
    at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by SingingBush** [comment]
plugin version 1.29.3 on IDEA CE 2022.3.2:

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1013)
    at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:424)
    at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:224)
    at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getText(LazyParseableElement.java:83)
    at com.intellij.psi.AbstractFileViewProvider$PsiFileContent.getText(AbstractFileViewProvider.java:514)
    at com.intellij.psi.AbstractFileViewProvider.getContents(AbstractFileViewProvider.java:158)
    at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:308)
    at io.github.intellij.dlanguage.codeinsight.dcd.DCDCompletionClient.autoComplete(DCDCompletionClient.java:77)
    at io.github.intellij.dlanguage.codeinsight.DCompletionProvider.lambda$addCompletions$2(DCompletionProvider.java:51)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
    at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by rikkimax** [comment]
Yes, I've been half putting it off to fix it due to it being marked deprecated. The other reason is it can take a while to exhibit, took over 25m before it showed up yesterday while programming (which is a massive improvement over every other minute getting an error!).

https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionClient.java#L77

While I can easily fix the EDT part, I don't know what to do about the deprecations. It seems there are other work that needs to go on.

**Comment by SingingBush** [comment]
there's been a few threading issues that have been intermittent making changes tricky to test. Any deprecations on the projects code can be ignored to some degree. I've ended up with a fair few local branches over the years for work that will likely not get finished off. A while ago I was considering moving away from the individual D tools and instead just relying on serve-d. I've not had time to make any substantial changes to the project for a while now. Fortunately Etienne has been contributing a great amount of work to keep the project going over the last 6 months.

**Comment by etienne02** [comment]
Yup, I want to improve native auto-completion after what I’m currently doing. If we could provide high quality native functionality without external tools. It will help to not have theses kind of problems we have currently.
