### ISSUE TITLE
error in the dub code on develop branch

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#826]
```
Cannot process toolwindow DubToolBar

java.lang.NullPointerException
	at java.base/java.util.Arrays.stream(Arrays.java:5614)
	at io.github.intellij.dub.toolwindow.DubToolWindow.isApplicable(DubToolWindow.kt:47)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:248)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt:278)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans(ToolWindowSetInitializer.kt:274)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:101)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:83)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by SingingBush** [comment]
https://github.com/intellij-dlanguage/intellij-dlanguage/commit/3624a9bbfec52ca5f4377244c5076336186e0ab1 prevents the null pointer but is hiding an underlying problem. When opening an existing dub project the dub tool window is available but creating a new dub project results in the tool window not being shown as the IDE is unable to correctly call _isApplicable_. Essentially the ToolWindowFactory needs the project files to be ready so that it can detect the existence of the dub.json or dub.sdl file. It seems _isApplicable_ is being called before this is possible.

**Comment by SingingBush** [comment]
the _ToolWindowFactory_ has a method called _isApplicable_ in which I've been using the following to detect either a `dub.json` or `dub.sdl` in the root of the project:

```kotlin
        val files = project.guessProjectDir()?.children ?: return false

        // when generating new projects the dub files don't exist yet!!!
        return Arrays.stream(files)
            .filter { f -> !f.isDirectory }
            .anyMatch { f -> "dub.json".equals(f.name, ignoreCase = true) || "dub.sdl".equals(f.name, ignoreCase = true) }
```

The most likely fix will be to instead just check the Sdk Type being used:

```kotlin
return ProjectRootManager.getInstance(project).projectSdk?.sdkType is DlangSdkType
```

but even that has issues as it's often the case that users don't have dmd setup as an sdk
