### ISSUE TITLE
DLangParser is attempting to parse *.d files in python installation

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#867]
There's a few times that reports have come in via sentry 

```
ava.lang.IllegalArgumentException: Could not find single match for token: 'floatLiteral'. 0 matches found
    at io.github.intellij.dlanguage.parser.DLangParser.tok(DLangParser.java:9465)
    at io.github.intellij.dlanguage.parser.DLangParser.<init>(DLangParser.java:135)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parseLight(ParserWrapper.java:23)
    at io.github.intellij.dlanguage.parser.ParserWrapper.parse(ParserWrapper.java:448)
```

It seems that for some reason Intellij is scanning the content of the users python installation. There are numerous files with a `.d` extension such as

 - test/dtracedata/assert_usable.d
 - test/dtracedata/call_stack.d
 - test/dtracedata/gc.d
 - test/dtracedata/line.d

which the IDE then treats as D source. This example was from Intellij IDEA Ultimate 2023.1.2 on Linux:

```
com.intellij.diagnostic.PluginException: Failed to build index 'DModuleIndex' for file file:///usr/lib/python3.10/test/dtracedata/line.d (id = 2365) (file type = D file) [Plugin: net.masterthought.dlanguage]
    at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
    at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
    at com.intellij.util.indexing.diagnostic.BrokenIndexingDiagnostics$DefaultListener.onFileIndexMappingFailed(BrokenIndexingDiagnostics.kt:47)
    at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1690)
    at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$26(FileBasedIndexImpl.java:1546)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:675)
    at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1494)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1467)
```

The plugin should only be treating `*.d` or `*.di` files as D source if it's files within the project under content roots or modules that have been added as D dependencies via dub.

**Comment by SingingBush** [comment]
got a similar error reported for `method_compile_stat.d` which is was related to dtrace files in Android source code

**Comment by SingingBush** [comment]
and another for `DynamicAny.idl.d` which is related to Java. I suspect that resolving this issue could close most of the [parser](https://github.com/intellij-dlanguage/intellij-dlanguage/issues?q=is%3Aissue+is%3Aopen+label%3Aparser) related issues

**Comment by SingingBush** [comment]
I've made a change for this on a local branch where I amend _DlangVirtualFileVisitor_'s _isExcluded_ method to do the following:

```java
        @Nullable final Project project = ProjectUtil.guessProjectForFile(srcFile);
        if(project != null) {
            final ProjectRootManager rootManager = ProjectRootManager.getInstance(project);
            @Nullable final Sdk sdk = rootManager.getProjectSdk();

            boolean notDlangSdk = !(sdk != null && (sdk.getSdkType() instanceof DlangSdkType));

            if(notDlangSdk) {
                log.debug(String.format("Visited file '%s' but excluding as project sdk is not a D lang SDK", srcFile.getName()));
            }
        }
```

I just need to do some testing before pushing the change

**Comment by SingingBush** [comment]
I'm going to merge some of the changes from the branch that was created for this but will actually leave out the part that detects if the current sdk is a DlangSdkType. I think it's overkill. Also I've not seen this error in a while. I'll leave the issue open for now but if there's no other incidents like this then it can just be closed.
