### ISSUE TITLE
tests occasionally timing out during gradle check

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#888]
running `./gradlew check` sometimes fails due to flakey tests. This is particularly a problem when targeting 2023.2. Giving gradle more memory can work around the issue but it would be better to fix the cause of the issue.

```
io.github.intellij.dlanguage.annotator.DHighlightingAnnotatorTest > testTypeParameters FAILED
    java.lang.RuntimeException: java.util.concurrent.TimeoutException
        at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:138)
        at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$doRunPasses$8(DaemonCodeAnalyzerImpl.java:487)
        at com.intellij.openapi.progress.impl.CoreProgressManager.suppressAllDeprioritizationsDuringLongTestsExecutionIn(CoreProgressManager.java:926)
        at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.doRunPasses(DaemonCodeAnalyzerImpl.java:434)
        at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.runPasses(DaemonCodeAnalyzerImpl.java:421)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$instantiateAndRun$7(CodeInsightTestFixtureImpl.java:289)
        at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.java:33)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.instantiateAndRun(CodeInsightTestFixtureImpl.java:288)
        at com.intellij.testFramework.fixtures.EditorTestFixture.doHighlighting(EditorTestFixture.java:163)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.doHighlighting(CodeInsightTestFixtureImpl.java:1731)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.collectAndCheckHighlighting(CodeInsightTestFixtureImpl.java:1697)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.collectAndCheckHighlighting(CodeInsightTestFixtureImpl.java:1670)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.collectAndCheckHighlighting(CodeInsightTestFixtureImpl.java:1657)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.testHighlighting(CodeInsightTestFixtureImpl.java:567)
        at io.github.intellij.dlanguage.annotator.DHighlightingAnnotatorTest.testTypeParameters(DHighlightingAnnotatorTest.kt:11)

        Caused by:
        java.util.concurrent.TimeoutException
            at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
            at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.waitInOtherThread(DaemonCodeAnalyzerImpl.java:539)
            at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$doRunPasses$8(DaemonCodeAnalyzerImpl.java:453)
            ... 13 more
```

before the stack trace there is a lot of output about:

```
    09:37:51,993 FINE   edIndexImpl$GentleIndexFlusher - Nothing to flush now: contention quota(16 -> 16) -> next turn scheduled regularly, with quota: 16 unchanged
```

which is preceded by:

```
com.intellij.psi.impl.source.tree.PsiWhiteSpaceImpl, parent = io.github.intellij.dlanguage.psi.DlangFile 
    10:01:06,906 FINE   tellij.psi.impl.PsiManagerImpl - childrenChanged: parent = io.github.intellij.dlanguage.psi.DlangFile 
    10:01:07,047 FINE   ij.psi.stubs.StubUpdatingIndex - Stub is built for temp:///src/invalid_string_delimiters.d, indexing timestamp = 39, binary = false, byte size = 602, char size = 600 
    10:01:07,048 FINE   vertiserExtensionsStateService - No known extensions loaded 
    10:01:07,048 FINE   vertiserExtensionsStateService - No known extensions loaded 
    10:01:07,049 FINE               #PluginsAdvertiser - Tried to update extensions cache for file 'unclosed_comment.d'. shouldUpdateNotifications=false 
    10:01:07,052 FINE   ij.psi.stubs.StubUpdatingIndex - Stub is built for temp:///src/invalid_string_delimiters.d, indexing timestamp = 39, binary = false, byte size = 602, char size = 154 
    10:01:07,059 FINE   aemon.impl.PassExecutorService -  null temp:///src/invalid_string_delimiters.d ----- starting 27 [SP: CodeFoldingPass; id=1, SP: IndentsPass; id=24, SP: CodeVisionPass; id=16, SP: InlayHintsPass; id=17, SP: DeclarativeInlayHintsPass; id=18, SP: VisualFormattingLayerHighlightingPass; id=28]; progress=1426930496 V 
    10:01:07,059 FINE   aemon.impl.PassExecutorService -  VisualFormattingLayerHighlightingPass; id=28 Started. ; progress=1426930496 V: ' 
     
    enum a =...' 
    10:01:07,059 FINE   aemon.impl.PassExecutorService -  CodeFoldingPass; id=1 Started. ; progress=1426930496 V: ' 
     
    enum a =...' 
    10:01:07,059 FINE   aemon.impl.PassExecutorService -  VisualFormattingLayerHighlightingPass; id=28 Finished. ; progress=1426930496 V: ' 
     
    enum a =...' 
    10:01:07,059 FINE   aemon.impl.PassExecutorService -  DeclarativeInlayHintsPass; id=18 Started. ; progress=1426930496 V: ' 
     
    enum a =...' 
    10:01:07,060 FINE   aemon.impl.PassExecutorService -  GeneralHighlightingPass; id=4 updateAll=true range=(0,154) Started. ; progress=1426930496 V: ' 
     
    enum a =...' 
    10:01:07,060 FINE   aemon.impl.PassExecutorService -  VisualFormattingLayerHighlightingPass; id=28  Applied; progress=1426930496 V: ' 
     
    enum a =...' 
    10:01:07,060 FINE   aemon.impl.PassExecutorService -  VisualFormattingLayerHighlightingPass; id=28 Finished but there are passes in the queue: 26; progress=1426930496 V: '
```

**Comment by SingingBush** [comment]
this is becoming a real problem for CI/CD. Not seeing the problem locally but it happens on github runners a lot

**Comment by SingingBush** [comment]
Commenting out [2 of the tests in DHighlightingAnnotatorTest.kt](https://github.com/intellij-dlanguage/intellij-dlanguage/commit/aff678dc3c838679cf2592a6e98f3be3144494b1) has made the build more reliable but it can still be a bit temperamental. It needs resolving properly.
