### ISSUE TITLE
Support for Intellij 2024.1

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#920]
The 1.33 release should support Intellij 2024.1. If the minimum-supported version needs to increase that's fine but ideally 2023 should still be supported if possible. 

So far only EAP releases are available for testing so it's not yet known if the failing build will continue to be a problem. 

GitHub Action failed with:

```
Error: Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/collections/immutable/PersistentList
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.<clinit>(ExtensionPointImpl.kt:71)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.doRegisterExtensionPoint(ExtensionsAreaImpl.kt:212)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.kt:186)
	at com.intellij.core.CoreApplicationEnvironment.registerExtensionPoint(CoreApplicationEnvironment.java:224)
	at com.intellij.core.CoreApplicationEnvironment.registerExtensionPoint(CoreApplicationEnvironment.java:214)
	at com.intellij.core.CoreApplicationEnvironment.registerApplicationExtensionPoint(CoreApplicationEnvironment.java:229)
	at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:93)
	at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:72)
	at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:152)
	at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:55)
	at org.intellij.grammar.Main.main(Main.java:38)
Caused by: java.lang.ClassNotFoundException: kotlinx.collections.immutable.PersistentList
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

**Comment by SingingBush** [comment]
2024.1 is out https://blog.jetbrains.com/idea/2024/04/intellij-idea-2024-1/

I've added it to the CI which currently fails due to the `:sdlang:generateSyntaxParser` task failing with the same stack trace as the previous comment.
