### ISSUE TITLE
Rendering of std.ascii is visually messed up

### ISSUE THREAD

**Issue by rikkimax** [intellij-dlanguage/intellij-dlanguage#934]
**Desktop (please provide environment info):**
 - OS: Windows 10
 - IDE: Intellij 2024.1
 - Plugin Version: 1.33.1

I've also had this in Linux Mint VM, it started with 2024.0.

**Describe the problem**

Visual artifacts make some files impossible to view.

**Please provide full details to reproduce the problem**

Open ``std.ascii`` and scroll, visually it will be messed up.

This is not specific to ``std.ascii`` its just an easy way to test it.

**Screenshots**

An example after scrolling, note the line numbers.

![Capture](https://github.com/intellij-dlanguage/intellij-dlanguage/assets/992755/e257f268-998b-49b1-b86c-54af00b4574b)

**Additional context**

I was able to extract the following from the log that shows the starting point.

```
2024-05-06 23:46:27,502 [  19957] SEVERE - #c.i.o.a.i.FlushQueue - Exception while applying information to Editor: file://C:/Tools/D/dmd_2.103.0/src/phobos/std/ascii.d(io.github.intellij.dlanguage.DlangFileType@af8db9d)
java.lang.RuntimeException: Exception while applying information to Editor: file://C:/Tools/D/dmd_2.103.0/src/phobos/std/ascii.d(io.github.intellij.dlanguage.DlangFileType@af8db9d)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$applyInformationToEditorsLater$2(PassExecutorService.java:515)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:204)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:419)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1152)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:123)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:699)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1022)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1022)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.Spliterators$2Adapter.nextInt(Spliterators.java:747)
	at com.intellij.codeInsight.documentation.DocumentationHtmlUtil$HtmlEditorPaneInputTranspiler.<init>(DocumentationHtmlUtil.kt:153)
	at com.intellij.codeInsight.documentation.DocumentationHtmlUtil.transpileForHtmlEditorPaneInput(DocumentationHtmlUtil.kt:136)
	at com.intellij.codeInsight.documentation.render.DocRenderer.createEditorPane(DocRenderer.java:311)
	at com.intellij.codeInsight.documentation.render.DocRenderer.getRendererComponent(DocRenderer.java:277)
	at com.intellij.codeInsight.documentation.render.DocRenderer.calcHeightInPixels(DocRenderer.java:138)
	at com.intellij.openapi.editor.impl.CustomFoldRegionImpl.doUpdate(CustomFoldRegionImpl.java:108)
	at com.intellij.openapi.editor.impl.CustomFoldRegionImpl.update(CustomFoldRegionImpl.java:75)
	at com.intellij.codeInsight.documentation.render.DocRenderer.lambda$update$0(DocRenderer.java:108)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.intellij.codeInsight.documentation.render.DocRenderItemUpdater.lambda$runFoldingTasks$6(DocRenderItemUpdater.java:91)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:299)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:240)
	at com.intellij.codeInsight.documentation.render.DocRenderItemUpdater.runFoldingTasks(DocRenderItemUpdater.java:91)
	at com.intellij.codeInsight.documentation.render.DocRenderItemUpdater.processChunk(DocRenderItemUpdater.java:80)
	at com.intellij.codeInsight.documentation.render.DocRenderItemUpdater.updateFoldRegions(DocRenderItemUpdater.java:48)
	at com.intellij.codeInsight.documentation.render.DocRenderItemUpdater.updateRenderers(DocRenderItemUpdater.java:31)
	at com.intellij.codeInsight.documentation.render.DocRenderItemManagerImpl.setItemsToEditor$lambda$4(DocRenderItemManagerImpl.kt:100)
	at com.intellij.codeInsight.documentation.render.DocRenderItemManagerImpl$Companion.keepScrollingPositionWhile(DocRenderItemManagerImpl.kt:179)
	at com.intellij.codeInsight.documentation.render.DocRenderItemManagerImpl$Companion.access$keepScrollingPositionWhile(DocRenderItemManagerImpl.kt:169)
	at com.intellij.codeInsight.documentation.render.DocRenderItemManagerImpl.setItemsToEditor(DocRenderItemManagerImpl.kt:60)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory.applyItemsToRender(DocRenderPassFactory.java:125)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory$DocRenderPass.doApplyInformationToEditor(DocRenderPassFactory.java:73)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.applyInformationToEditor(TextEditorHighlightingPass.java:106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$applyInformationToEditorsLater$2(PassExecutorService.java:498)
	... 42 more
```

**Comment by etienne02** [comment]
I did some checks and it’s clearly a regression of intellij, not the plugin. They do a nextInt without first checking that the iterator contains a next element. The case appears for empty lines of documentation being transformed into html (pretty printed).

**Comment by rikkimax** [comment]
I'm surprised that they didn't catch that with their own plugins.

I bet it won't be a pleasant bug to report to them.

We are pretty heavily impacted since D is heavily documented in comparison to a lot of languages.

**Comment by rikkimax** [comment]
As of Intellij 2024.1.2 this has been fixed.
