### ISSUE TITLE
AlreadyDisposedException in DScanner::onTextAvailable attempting to parse issue when container already disposed

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#998]
plugin version: 1.34.3 in IDEA 2024.2

```
com.intellij.serviceContainer.AlreadyDisposedException: Container is already disposed
    at com.intellij.serviceContainer.ComponentManagerImplKt.throwAlreadyDisposedIfNotUnderIndicatorOrJob(ComponentManagerImpl.kt:1672)
    at com.intellij.serviceContainer.ComponentManagerImplKt.access$throwAlreadyDisposedIfNotUnderIndicatorOrJob(ComponentManagerImpl.kt:1)
    at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:716)
    at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
    at com.intellij.psi.PsiDocumentManager.getInstance(PsiDocumentManager.java:37)
    at io.github.intellij.dlanguage.highlighting.annotation.external.LinterHelper.calculateTextRange(LinterHelper.java:51)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner.parseProblem(DScanner.java:166)
    at io.github.intellij.dlanguage.highlighting.annotation.external.DScanner$1.onTextAvailable(DScanner.java:103)
    at com.intellij.execution.process.ProcessHandler$2.onTextAvailable(ProcessHandler.java:292)
    at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:223)
    at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:133)
    at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:220)
    at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:204)
    at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:116)
    at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:72)
    at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:153)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
    at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:48)
```

probably just need to ensure file isn't disposed: 
https://github.com/intellij-dlanguage/intellij-dlanguage/blob/4547c497ca2d5a55504ed40ef0ae057f9c777369/src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/DScanner.java#L100-L112

**Comment by SingingBush** [comment]
https://github.com/intellij-dlanguage/intellij-dlanguage/commit/546dfc2a9953e4256daa4d20fe4b69a2a3ce0adc
